In [2]:
from sklearn.datasets import load_files
import pandas as pd

# malaylam and tamil file is combined in excel and sorted ascedning by column Tweet so that tweets from both language got mixed

In [3]:
Mal_Tam_data=pd.read_excel("Malayalam + Tamil.xlsx" , header=None)

In [4]:
Mal_Tam_data[20:30]

0                                                  1    2
20  TA_HL1013  ( indha award function la munnadi seat la unka...  OFF
21   TA_TW850  ***mmala Silent ah Navundhuru Wanted varadha U...  NOT
22  TA_TW2408  *Ladies...when he tells you....shake what your...  OFF
23   TA_TW586  *listening to havana* appa - "enna paatu kekra...  NOT
24  MA_YT3007  *sangappifalk*um *moori*galkum palaozum ithine...  OFF
25  MA_YT2450  , cashine vendi ningal mathathe upayogichu, or...  OFF
26  TA_HL1012  .. chai ipdila pesadhinga appangra sthanam chi...  NOT
27  TA_TW6109  .. Yaaru @USER sir ah.. Idha ellam paaka nalla...  NOT
28   TA_TW956  .. Yaaru @USER sir ah.. Idha ellam paaka nalla...  NOT
29  MA_YT2726  ... pala pala karyangalil.. self financing.. c...  NOT

In [5]:
Mal_Tam_data[4020:4030]

0                                                  1    2
4020  TA_TW6403  Ellarum Saptacha ..??? *** : Yen Sapadu Vangi ...  NOT
4021  MA_YT3006  ellarum swandam mathathil vishwasikkunnu.. por...  NOT
4022   TA_HL324  ellarum veruthutinga... ha ha ha.... enakkum n...  NOT
4023   TA_HL325  ellarum wrk pannanumthan slirukanga so athanal...  NOT
4024  MA_YT2898  ellathilum negative kanunna malayalikalk ninan...  NOT
4025  MA_YT1927  Ellathinem oru roomil pootiyititt coronaye ket...  OFF
4026  MA_YT3995  Ellavarkum avrde sundaryamind...inganeparayan ...  NOT
4027  MA_YT3382  ellavarudem perokke marannu poyi eni ellam ran...  NOT
4028  MA_YT2303  Ellavarum dislike cheyyu... Ee pezhakale YouTu...  OFF
4029  MA_YT2269                    Ellavarum kundiyillotta nokkiye  OFF

In [6]:
Mal_Tam_data=Mal_Tam_data.rename(columns={0:'ID', 1:'Tweets', 2:'Labels'})

In [7]:
import regex
import re
import numpy as np

In [8]:
labels,counts=np.unique(Mal_Tam_data['Labels'],return_counts=True)
print(labels,counts)

['Labels' 'NOT' 'OFF' 'OFf' 'not'] [   1 4066 3932    1    1]


In [9]:
lab=Mal_Tam_data['Labels']
lab

0       OFF
1       NOT
2       NOT
3       OFF
4       NOT
       ... 
7996    OFF
7997    OFF
7998    OFF
7999    NOT
8000    OFF
Name: Labels, Length: 8001, dtype: object

In [10]:
low_lab=lab.str.lower()
low_lab

0       off
1       not
2       not
3       off
4       not
       ... 
7996    off
7997    off
7998    off
7999    not
8000    off
Name: Labels, Length: 8001, dtype: object

In [11]:
Lowlabels=pd.DataFrame(low_lab)
Lowlabels.columns=['Lowlabels']
Lowlabels

Lowlabels
0          off
1          not
2          not
3          off
4          not
...        ...
7996       off
7997       off
7998       off
7999       not
8000       off

[8001 rows x 1 columns]

In [12]:
Mal_Tam_data=pd.concat([Mal_Tam_data, Lowlabels], axis=1)
Mal_Tam_data

ID                                             Tweets Labels  \
0     TA_TW2403  #TAG #TAG elumban fans vaai punda athigam than...    OFF   
1     TA_TW1685  #TAG @USER vandha valiya marakama ellaa stage ...    NOT   
2      TA_TW429  #TAG After hearing the song,thumbi thullucho n...    NOT   
3     TA_TW2404  #TAG andha police naingala thookula podanum......    OFF   
4      TA_TW656  #TAG Anna post pottu 1Week ku mela aachu ... E...    NOT   
...         ...                                                ...    ...   
7996  MA_YT1700                 Yukthivsthathil incest allowed aan    OFF   
7997  TA_HL1010  yullaa onumayaa podulaiyaa apdiyaa boots triyu...    OFF   
7998  TA_HL1011   zoola irukka vendiyathulaam paduthula nadikkuthu    OFF   
7999   MA_YT168  😆😆allam kaayinnu poyi😆😆 Ah motta chettanu ente...    NOT   
8000  MA_YT1381                                                NaN    OFF   

     Lowlabels  
0          off  
1          not  
2          not  
3          off  
4          not  
...        ...  
7996       off  
7997       off  
7998       off  
7999       not  
8000       off  

[8001 rows x 4 columns]

In [13]:
Mal_Tam_data['Lowlabels']=Mal_Tam_data['Lowlabels'].apply(lambda x: 1 if x=="off" else 0)

In [14]:
Mal_Tam_data

ID                                             Tweets Labels  \
0     TA_TW2403  #TAG #TAG elumban fans vaai punda athigam than...    OFF   
1     TA_TW1685  #TAG @USER vandha valiya marakama ellaa stage ...    NOT   
2      TA_TW429  #TAG After hearing the song,thumbi thullucho n...    NOT   
3     TA_TW2404  #TAG andha police naingala thookula podanum......    OFF   
4      TA_TW656  #TAG Anna post pottu 1Week ku mela aachu ... E...    NOT   
...         ...                                                ...    ...   
7996  MA_YT1700                 Yukthivsthathil incest allowed aan    OFF   
7997  TA_HL1010  yullaa onumayaa podulaiyaa apdiyaa boots triyu...    OFF   
7998  TA_HL1011   zoola irukka vendiyathulaam paduthula nadikkuthu    OFF   
7999   MA_YT168  😆😆allam kaayinnu poyi😆😆 Ah motta chettanu ente...    NOT   
8000  MA_YT1381                                                NaN    OFF   

      Lowlabels  
0             1  
1             0  
2             0  
3             1  
4             0  
...         ...  
7996          1  
7997          1  
7998          1  
7999          0  
8000          1  

[8001 rows x 4 columns]

In [15]:
msg=Mal_Tam_data['Tweets']

In [16]:
# Removing all emojis from tweets by using the emojis code 
msg_emoj=msg.str.replace(r'[(\U0001F600-\U0001F92F|\U0001F300-\U0001F5FF|\U0001F680-\U0001F6FF|\U0001F190-\U0001F1FF|\U00002702-\U000027B0|\U0001F926-\U0001FA9F|\u200d|\u2640-\u2642|\u2600-\u2B55|\u23cf|\u23e9|\u231a|\ufe0f)]+','')
msg_emoj[3830:3840]

3830                 e pottanu vote cheyunavare thallanam
3831    e puliyaadimon aanu vargeya vadhi thayoli kuth...
3832    E rema ashiaq,abu aanu bhavanye rashikkan nilk...
3833              E sadika arannu enike epozhum doubt anu
3834    E sambhavam mukkiA madhAmangalkethire case edu...
3835    E sangi congi pongi ennoke paranjal pennint po...
3836                      e thayolik penmakkal onnum ille
3837    E video eduthavan.....................#@$#$$:"...
3838    E...barthavineyum bhariyeneyum odikan arumile....
3839    ea..poallayadeacheakkallea....veacheakaruthe.....
Name: Tweets, dtype: object

In [17]:
# Removing @USER at the start of each tweet
msg_USER_TAG=msg_emoj.str.replace(r"@USER |RT| #TAG", ' ')
#Chceking from tamil dataset whether @USER, @RT and @TAG are removed..?
msg_USER_TAG[1:10]

1    #TAG  vandha valiya marakama ellaa stage la yu...
2    #TAG After hearing the song,thumbi thullucho n...
3    #TAG andha police naingala thookula podanum......
4    #TAG Anna post pottu 1Week ku mela aachu ... E...
5    #TAG censor board team kuda wish panirukanga a...
6    #TAG Enna ba idhu? Ipdi panniputeenga? Poll po...
7    #TAG fuck you Tamilnadu police you and your gu...
8    #TAG Intha ulagathilla romba easyyaana Visayam...
9    #TAG mami returns with tempting hot age analum...
Name: Tweets, dtype: object

In [18]:
#Chceking from Malaylam dataset whether @USER is removed..?
msg_USER_TAG[200:208]

200     Adeiii enna issthunu poda ottagaa paal la tea...
201     Adengappa unaku irukura followers ku inike ne...
202     Adengappa unaku irukura followers ku inike ne...
203     Adengappa. Unaku arivu illanu theriyum. Aana ...
204     adhellam kanake illadha alavuku pathachu.. Se...
205     adhepdi ne sollalam innum 1 r 2 years nu. and...
206     Adhu epidi postpone ... Ne yaarula anna unive...
207     Adhu irukattum andha mangatha la gundan dhan ...
Name: Tweets, dtype: object

In [142]:
# Encoding  😁😁 & many other symbols to ASCII; so that those r removed from tweets. 
# After removal we can see msg is encoded and started with b'
msg_USER_Encod=msg_USER_TAG.str.encode("ascii", "ignore")
msg_USER_Encod[200:208], type(msg_USER_Encod)

(200    b' Adeiii enna issthunu poda ottagaa paal la t...
 201    b' Adengappa unaku irukura followers ku inike ...
 202    b' Adengappa unaku irukura followers ku inike ...
 203    b' Adengappa. Unaku arivu illanu theriyum. Aan...
 204    b' adhellam kanake illadha alavuku pathachu.. ...
 205    b' adhepdi ne sollalam innum 1 r 2 years nu. a...
 206    b' Adhu epidi postpone ... Ne yaarula anna uni...
 207    b' Adhu irukattum andha mangatha la gundan dha...
 Name: Tweets, dtype: object, pandas.core.series.Series)

In [143]:
# Decoding msg to format where we can see b' is removed 
msg_USER_decod=msg_USER_Encod.str.decode(encoding = 'ASCII')
msg_USER_decod[200:208]

200     Adeiii enna issthunu poda ottagaa paal la tea...
201     Adengappa unaku irukura followers ku inike ne...
202     Adengappa unaku irukura followers ku inike ne...
203     Adengappa. Unaku arivu illanu theriyum. Aana ...
204     adhellam kanake illadha alavuku pathachu.. Se...
205     adhepdi ne sollalam innum 1 r 2 years nu. and...
206     Adhu epidi postpone ... Ne yaarula anna unive...
207     Adhu irukattum andha mangatha la gundan dhan ...
Name: Tweets, dtype: object

In [144]:
# Removing digits 
msg_Digit = msg_USER_decod.str.replace(r'[0-9]', ' ')
msg_Digit[7080:7081]

7080       Dei poolu illa thevidiya Paiyan poi ungomma...
Name: Tweets, dtype: object

In [145]:
# Removing Special Characters
msg_SpChar = msg_Digit.str.replace(r'[^\w\d\s]', ' ')
print(msg_SpChar[51])

   Moly VALLODATHU NINNUM VALINJU KAYARI VANNITTU KONAKKUNNODA MYRE NINTE THALLAYEYUM PENGALEYUM BHARYAYEYUM KUNDIYUM MULAYUM ADICHU POLICHU KALAYUM NJAN


In [146]:
# Removing  Hyphens & xtra Whitespaces 
msg_Spac = msg_SpChar.str.replace(r'\s+', ' ')
msg_Hyp = msg_Spac.str.replace(r'_','')

In [147]:
# storing msg_spec (i.e. processed data) into dataframe Msg_df
Msg_df=pd.DataFrame(msg_Hyp)
Msg_df.columns=['Msg_with_Stopwords']

In [148]:
# Removing Null values 
Msg_df['Msg_with_Stopwords']=Msg_df['Msg_with_Stopwords'].fillna("")

In [149]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [150]:
# Removing Stop words 
stop_words = set(stopwords.words('english'))

In [151]:
Msg_df['Msg_without_Stopwords']=Msg_df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [152]:
Msg_df['Msg_without_Stopwords']

0       TAG elumban fans vaai punda athigam suriya ann...
1       TAG vandha valiya marakama ellaa stage la yum ...
2       TAG After hearing song thumbi thullucho nu the...
3       TAG andha police naingala thookula podanum ill...
4       TAG Anna post pottu Week ku mela aachu Enna nu...
                              ...                        
7996                   Yukthivsthathil incest allowed aan
7997    yullaa onumayaa podulaiyaa apdiyaa boots triyu...
7998     zoola irukka vendiyathulaam paduthula nadikkuthu
7999    allam kaayinnu poyi Ah motta chettanu ente vak...
8000                                                     
Name: Msg_without_Stopwords, Length: 8001, dtype: object

In [153]:
# Counting length of each tweet  with stopwords and without stopwords 
Msg_df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_with_Stopwords'].tolist()]
Msg_df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_without_Stopwords'].tolist()]

In [154]:
Msg_df

Msg_with_Stopwords  \
0      TAG elumban fans vaai punda athigam than suri...   
1      TAG vandha valiya marakama ellaa stage la yum...   
2      TAG After hearing the song thumbi thullucho n...   
3      TAG andha police naingala thookula podanum il...   
4      TAG Anna post pottu Week ku mela aachu Enna n...   
...                                                 ...   
7996                 Yukthivsthathil incest allowed aan   
7997  yullaa onumayaa podulaiyaa apdiyaa boots triyu...   
7998   zoola irukka vendiyathulaam paduthula nadikkuthu   
7999  allam kaayinnu poyi Ah motta chettanu ente vak...   
8000                                                      

                                  Msg_without_Stopwords  \
0     TAG elumban fans vaai punda athigam suriya ann...   
1     TAG vandha valiya marakama ellaa stage la yum ...   
2     TAG After hearing song thumbi thullucho nu the...   
3     TAG andha police naingala thookula podanum ill...   
4     TAG Anna post pottu Week ku mela aachu Enna nu...   
...                                                 ...   
7996                 Yukthivsthathil incest allowed aan   
7997  yullaa onumayaa podulaiyaa apdiyaa boots triyu...   
7998   zoola irukka vendiyathulaam paduthula nadikkuthu   
7999  allam kaayinnu poyi Ah motta chettanu ente vak...   
8000                                                      

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  
0                         12                         11  
1                         13                         13  
2                         28                         20  
3                         33                         33  
4                         25                         25  
...                      ...                        ...  
7996                       4                          4  
7997                       7                          7  
7998                       5                          5  
7999                      11                         11  
8000                       0                          0  

[8001 rows x 4 columns]

In [155]:
# Concatinating original dataframe i.e. Mal_Tam_data and modified dataframes i.e. Msg_df into final_Data
final_Data=pd.concat([Msg_df, Mal_Tam_data], axis=1)
final_Data

Msg_with_Stopwords  \
0      TAG elumban fans vaai punda athigam than suri...   
1      TAG vandha valiya marakama ellaa stage la yum...   
2      TAG After hearing the song thumbi thullucho n...   
3      TAG andha police naingala thookula podanum il...   
4      TAG Anna post pottu Week ku mela aachu Enna n...   
...                                                 ...   
7996                 Yukthivsthathil incest allowed aan   
7997  yullaa onumayaa podulaiyaa apdiyaa boots triyu...   
7998   zoola irukka vendiyathulaam paduthula nadikkuthu   
7999  allam kaayinnu poyi Ah motta chettanu ente vak...   
8000                                                      

                                  Msg_without_Stopwords  \
0     TAG elumban fans vaai punda athigam suriya ann...   
1     TAG vandha valiya marakama ellaa stage la yum ...   
2     TAG After hearing song thumbi thullucho nu the...   
3     TAG andha police naingala thookula podanum ill...   
4     TAG Anna post pottu Week ku mela aachu Enna nu...   
...                                                 ...   
7996                 Yukthivsthathil incest allowed aan   
7997  yullaa onumayaa podulaiyaa apdiyaa boots triyu...   
7998   zoola irukka vendiyathulaam paduthula nadikkuthu   
7999  allam kaayinnu poyi Ah motta chettanu ente vak...   
8000                                                      

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len         ID  \
0                         12                         11  TA_TW2403   
1                         13                         13  TA_TW1685   
2                         28                         20   TA_TW429   
3                         33                         33  TA_TW2404   
4                         25                         25   TA_TW656   
...                      ...                        ...        ...   
7996                       4                          4  MA_YT1700   
7997                       7                          7  TA_HL1010   
7998                       5                          5  TA_HL1011   
7999                      11                         11   MA_YT168   
8000                       0                          0  MA_YT1381   

                                                 Tweets Labels  Lowlabels  
0     #TAG #TAG elumban fans vaai punda athigam than...    OFF          1  
1     #TAG @USER vandha valiya marakama ellaa stage ...    NOT          0  
2     #TAG After hearing the song,thumbi thullucho n...    NOT          0  
3     #TAG andha police naingala thookula podanum......    OFF          1  
4     #TAG Anna post pottu 1Week ku mela aachu ... E...    NOT          0  
...                                                 ...    ...        ...  
7996                 Yukthivsthathil incest allowed aan    OFF          1  
7997  yullaa onumayaa podulaiyaa apdiyaa boots triyu...    OFF          1  
7998   zoola irukka vendiyathulaam paduthula nadikkuthu    OFF          1  
7999  😆😆allam kaayinnu poyi😆😆 Ah motta chettanu ente...    NOT          0  
8000                                                NaN    OFF          1  

[8001 rows x 8 columns]

In [156]:
# Dropping the columns Tweets and ID
final_Data=final_Data.drop(['Tweets', 'ID', 'Labels'], axis=1)
final_Data

Msg_with_Stopwords  \
0      TAG elumban fans vaai punda athigam than suri...   
1      TAG vandha valiya marakama ellaa stage la yum...   
2      TAG After hearing the song thumbi thullucho n...   
3      TAG andha police naingala thookula podanum il...   
4      TAG Anna post pottu Week ku mela aachu Enna n...   
...                                                 ...   
7996                 Yukthivsthathil incest allowed aan   
7997  yullaa onumayaa podulaiyaa apdiyaa boots triyu...   
7998   zoola irukka vendiyathulaam paduthula nadikkuthu   
7999  allam kaayinnu poyi Ah motta chettanu ente vak...   
8000                                                      

                                  Msg_without_Stopwords  \
0     TAG elumban fans vaai punda athigam suriya ann...   
1     TAG vandha valiya marakama ellaa stage la yum ...   
2     TAG After hearing song thumbi thullucho nu the...   
3     TAG andha police naingala thookula podanum ill...   
4     TAG Anna post pottu Week ku mela aachu Enna nu...   
...                                                 ...   
7996                 Yukthivsthathil incest allowed aan   
7997  yullaa onumayaa podulaiyaa apdiyaa boots triyu...   
7998   zoola irukka vendiyathulaam paduthula nadikkuthu   
7999  allam kaayinnu poyi Ah motta chettanu ente vak...   
8000                                                      

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  Lowlabels  
0                         12                         11          1  
1                         13                         13          0  
2                         28                         20          0  
3                         33                         33          1  
4                         25                         25          0  
...                      ...                        ...        ...  
7996                       4                          4          1  
7997                       7                          7          1  
7998                       5                          5          1  
7999                      11                         11          0  
8000                       0                          0          1  

[8001 rows x 5 columns]

In [157]:
# splitting the dataset into train=70% & test=30% where X=final_Data.Msg_without_Stopwords & Y=final_Data.Labels
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(final_Data.Msg_without_Stopwords, final_Data.Lowlabels,  random_state=40, test_size=0.3)

In [158]:
len(X_train), len(y_train), len(X_test), len(y_test)

(5600, 5600, 2401, 2401)

In [159]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(analyzer='word', lowercase=True, ngram_range=(1,6))
X=tfidf.fit_transform(X_train)
Y=y_train
tfidf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 6), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [160]:
char_tfidf=TfidfVectorizer(analyzer='char', lowercase=True, ngram_range=(1, 8))
X_char=char_tfidf.fit_transform(X_train) 
char_tfidf

TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 8), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [161]:
# No of features extracted 
len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())

(282975, 862753)

In [162]:
tfidf.get_feature_names()

['aa',
 'aa aala',
 'aa aala thanna',
 'aa aala thanna alla',
 'aa aala thanna alla matruka',
 'aa aala thanna alla matruka aakkunnathu',
 'aa accountinte',
 'aa accountinte aalu',
 'aa accountinte aalu thanne',
 'aa accountinte aalu thanne annu',
 'aa accountinte aalu thanne annu trolling',
 'aa adhamanaya',
 'aa adhamanaya nadanodu',
 'aa adhamanaya nadanodu paranhittu',
 'aa adhamanaya nadanodu paranhittu kariyamolla',
 'aa adhamanaya nadanodu paranhittu kariyamolla sir',
 'aa adikkan',
 'aa adikkan pattu',
 'aa adikkan pattu alllakil',
 'aa adikkan pattu alllakil oru',
 'aa adikkan pattu alllakil oru million',
 'aa adisthanathil',
 'aa adisthanathil pooran',
 'aa adisthanathil pooran security',
 'aa adisthanathil pooran security ella',
 'aa adisthanathil pooran security ella penungalem',
 'aa athellame',
 'aa athellame solli',
 'aa athellame solli thitra',
 'aa athellame solli thitra ungamma',
 'aa athellame solli thitra ungamma koothi',
 'aa avar',
 'aa avar orupad',
 'aa avar oru

In [163]:
char_tfidf.get_feature_names()

[' ',
 ' a',
 ' a ',
 ' a c',
 ' a ch',
 ' a cha',
 ' a chal',
 ' a chali',
 ' a e',
 ' a en',
 ' a enn',
 ' a enn ',
 ' a enn p',
 ' a g',
 ' a go',
 ' a goo',
 ' a good',
 ' a good ',
 ' a n',
 ' a ne',
 ' a neg',
 ' a nega',
 ' a negat',
 ' a o',
 ' a ot',
 ' a oth',
 ' a otha',
 ' a othaa',
 ' a t',
 ' a th',
 ' a thr',
 ' a thre',
 ' a threa',
 ' aa',
 ' aa ',
 ' aa a',
 ' aa aa',
 ' aa aal',
 ' aa aala',
 ' aa ac',
 ' aa acc',
 ' aa acco',
 ' aa ad',
 ' aa adi',
 ' aa adik',
 ' aa adis',
 ' aa at',
 ' aa ath',
 ' aa athe',
 ' aa b',
 ' aa ba',
 ' aa baa',
 ' aa baal',
 ' aa be',
 ' aa bed',
 ' aa bedi',
 ' aa c',
 ' aa ca',
 ' aa cas',
 ' aa casa',
 ' aa ci',
 ' aa cin',
 ' aa cine',
 ' aa d',
 ' aa da',
 ' aa da ',
 ' aa da n',
 ' aa da u',
 ' aa dh',
 ' aa dha',
 ' aa dhan',
 ' aa du',
 ' aa dup',
 ' aa dupl',
 ' aa f',
 ' aa fi',
 ' aa fil',
 ' aa film',
 ' aa g',
 ' aa ga',
 ' aa gat',
 ' aa gath',
 ' aa gay',
 ' aa gaya',
 ' aa i',
 ' aa ir',
 ' aa iru',
 ' aa iruk',
 ' aa i

In [164]:
len(tfidf.vocabulary_), len(char_tfidf.vocabulary_), len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())

(282975, 862753, 282975, 862753)

In [165]:
X, X_char

(<5600x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 356362 stored elements in Compressed Sparse Row format>,
 <5600x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 3222473 stored elements in Compressed Sparse Row format>)

In [166]:
from scipy.sparse import hstack
train=hstack([X,X_char])
train

<5600x1145728 sparse matrix of type '<class 'numpy.float64'>'
	with 3578835 stored elements in COOrdinate format>

In [167]:
Xt=tfidf.transform(X_test) 
Xt_char=char_tfidf.transform(X_test) 

In [168]:
Xt, Xt_char

(<2401x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 42366 stored elements in Compressed Sparse Row format>,
 <2401x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 1119428 stored elements in Compressed Sparse Row format>)

In [169]:
traintest=hstack([Xt,Xt_char])
traintest

<2401x1145728 sparse matrix of type '<class 'numpy.float64'>'
	with 1161794 stored elements in COOrdinate format>

In [170]:
mal_hasoc=pd.read_excel("Tamil+Malya.xlsx", header=None)
mal_hasoc=mal_hasoc.rename(columns={0:'ID', 1:'Tweets'})
test_Mal_Hasoc=mal_hasoc['Tweets']

test_Mal_Hasoc_word=tfidf.transform(test_Mal_Hasoc)
test_Mal_Hasoc_char=char_tfidf.transform(test_Mal_Hasoc)
test_Mal_Hasoc_word_char=hstack([test_Mal_Hasoc_word,test_Mal_Hasoc_char])

In [171]:
test_Mal_Hasoc_word, test_Mal_Hasoc_char, test_Mal_Hasoc_word_char

(<1940x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 18823 stored elements in Compressed Sparse Row format>,
 <1940x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 837874 stored elements in Compressed Sparse Row format>,
 <1940x1145728 sparse matrix of type '<class 'numpy.float64'>'
 	with 856697 stored elements in COOrdinate format>)

In [172]:
test_Mal_Hasoc_word, test_Mal_Hasoc_char, test_Mal_Hasoc_word_char

(<1940x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 18823 stored elements in Compressed Sparse Row format>,
 <1940x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 837874 stored elements in Compressed Sparse Row format>,
 <1940x1145728 sparse matrix of type '<class 'numpy.float64'>'
 	with 856697 stored elements in COOrdinate format>)

In [173]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [174]:
def trainer(model_obj, param, X, X_char, train, traintest, Y, y_test):
    
    GSCV=GridSearchCV(model_obj, param , cv=5,return_train_score=False)
    GSCV.fit(X,Y)
    #Training Classifier with TF-IDF Features Word n-gram
    #model_obj.fit(X,Y)
    print("Accuracy of Word n-gram(1,6) :", (GSCV.score(tfidf.transform(X_test), y_test)))
    #Printing Classification Report
    predict=GSCV.predict(Xt)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=GSCV.predict(test_Mal_Hasoc_word)


  #Training Classifier with TF-IDF Features Char n-gram
    GSCV.fit(X_char, Y)
    print("Accuracy of Char n-gram(1,8) :", (GSCV.score(char_tfidf.transform(X_test), y_test)))
    predict=GSCV.predict(Xt_char)
    print(classification_report(y_test, predict))
   #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=GSCV.predict(test_Mal_Hasoc_char)

        
              
    #Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    GSCV.fit(train, Y)
    print("Accuracy of Combinining word & Char n-gram", (GSCV.score(traintest, y_test)))
    #Printing Classification Report
    predict=GSCV.predict(traintest)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=GSCV.predict(test_Mal_Hasoc_word_char)
    
    return word, char, word_char

# Implementing SVC

In [175]:
from sklearn.svm import SVC
svc=SVC()
print("SVC")
param={'kernel':('linear', 'rbf'), 'gamma':('auto', 'scale'), 'C':[0.9, 10, 20, 30]}
w_svc,c_svc,wc_svc=trainer(svc,param, X, X_char, train, traintest, Y, y_test)

SVC
Accuracy of Word n-gram(1,6) : 0.7671803415243649
              precision    recall  f1-score   support

           0       0.74      0.81      0.78      1191
           1       0.80      0.72      0.76      1210

    accuracy                           0.77      2401
   macro avg       0.77      0.77      0.77      2401
weighted avg       0.77      0.77      0.77      2401

Best Parameters  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'}
Best Score  0.7633928571428571
 
Confusion Matrix
[[965 226]
 [333 877]]
 
Accuracy of Char n-gram(1,8) : 0.7859225322782174
              precision    recall  f1-score   support

           0       0.77      0.81      0.79      1191
           1       0.80      0.77      0.78      1210

    accuracy                           0.79      2401
   macro avg       0.79      0.79      0.79      2401
weighted avg       0.79      0.79      0.79      2401

Best Parameters  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Best Score  0.7930357142857143
 
Confusio

In [178]:
wc_svc=pd.DataFrame(wc_svc, columns=["Combine Word Char_SVC"])
mal_tam=pd.concat([mal_hasoc, wc_svc['Combine Word Char_SVC']], axis=1)
mal_tam['Combine Word Char_SVC'] = mal_tam['Combine Word Char_SVC'].map({0 : 'NOT', 1 : 'OFF'})

mal_tam.to_csv("Mal_Tamil_SVC_Results.xlsx")

In [179]:
mal_tam

ID                                             Tweets  \
0     MA_YT5000               Chenkol vendath thanne aayirunnu....   
1     MA_YT5001              Sundardasinte bhakshnam vakkukal ano?   
2     MA_YT5002  Akasha dooth oru copy adi movie anu 'Who will ...   
3     MA_YT5003  Purath onnum pondade... oru pennum payyanum on...   
4     MA_YT5004  Avasanam Fahad oru Oscar medikkumbazhum lalett...   
...         ...                                                ...   
1935  TA_TW9701  RT  : Engineering Mudichu 2 years ayuruchu Adh...   
1936  TA_TW9702  To  #TAG oruthanvagaloda saavula kooda controv...   
1937  TA_TW9703  Veetla matna.. Reason illama 6year love Thooki...   
1938  TA_TW9704   Neenga enkitta pesalam vena "indu madham enge...   
1939  TA_TW9705   Kantha sasti kavasatha, neenga konjam thamizh...   

     Combine Word Char_SVC  
0                      NOT  
1                      NOT  
2                      NOT  
3                      NOT  
4                      OFF  
...                    ...  
1935                   NOT  
1936                   NOT  
1937                   OFF  
1938                   NOT  
1939                   NOT  

[1940 rows x 3 columns]

# Implementing Multinomial Naive Bayes 

In [176]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB(alpha=2.0)
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train, traintest, Y, y_test)

Multi Nominal Bayes
Accuracy of Word n-gram(1,6) : 0.7650978758850479
              precision    recall  f1-score   support

           0       0.73      0.84      0.78      1191
           1       0.81      0.69      0.75      1210

    accuracy                           0.77      2401
   macro avg       0.77      0.77      0.76      2401
weighted avg       0.77      0.77      0.76      2401

Best Parameters  {'alpha': 0.5}
Best Score  0.76375
 
Confusion Matrix
[[1001  190]
 [ 374  836]]
 
Accuracy of Char n-gram(1,8) : 0.7788421491045397
              precision    recall  f1-score   support

           0       0.74      0.85      0.79      1191
           1       0.83      0.71      0.76      1210

    accuracy                           0.78      2401
   macro avg       0.78      0.78      0.78      2401
weighted avg       0.78      0.78      0.78      2401

Best Parameters  {'alpha': 0.5}
Best Score  0.7951785714285714
 
Confusion Matrix
[[1012  179]
 [ 352  858]]
 
Accuracy of Com

In [119]:
wc_mnb=pd.DataFrame(wc_mnb, columns=["Combine Word Char_MNB"])
mal_tam=pd.concat([mal_hasoc, wc_mnb['Combine Word Char_MNB']], axis=1)
mal_tam['Combine Word Char_MNB'] = mal_tam['Combine Word Char_MNB'].map({0 : 'NOT', 1 : 'OFF'})

mal_tam.to_csv("Mal_Tamil_MNB_Results.xlsx")

In [120]:
mal_tam

ID                                             Tweets  \
0     MA_YT5000               Chenkol vendath thanne aayirunnu....   
1     MA_YT5001              Sundardasinte bhakshnam vakkukal ano?   
2     MA_YT5002  Akasha dooth oru copy adi movie anu 'Who will ...   
3     MA_YT5003  Purath onnum pondade... oru pennum payyanum on...   
4     MA_YT5004  Avasanam Fahad oru Oscar medikkumbazhum lalett...   
...         ...                                                ...   
1935  TA_TW9701  RT  : Engineering Mudichu 2 years ayuruchu Adh...   
1936  TA_TW9702  To  #TAG oruthanvagaloda saavula kooda controv...   
1937  TA_TW9703  Veetla matna.. Reason illama 6year love Thooki...   
1938  TA_TW9704   Neenga enkitta pesalam vena "indu madham enge...   
1939  TA_TW9705   Kantha sasti kavasatha, neenga konjam thamizh...   

     Combine Word Char_MNB  
0                      NOT  
1                      NOT  
2                      NOT  
3                      NOT  
4                      NOT  
...                    ...  
1935                   NOT  
1936                   NOT  
1937                   OFF  
1938                   NOT  
1939                   NOT  

[1940 rows x 3 columns]

# Implementing Logistic Regression 

In [180]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(random_state=40, solver='lbfgs')
param={'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'), 'multi_class':('ovr', 'auto')}
print("Logisitc Regression")
w_lr,c_lr,wc_lr=trainer(LR,param, X, X_char, train, traintest, Y, y_test)

Logisitc Regression
Accuracy of Word n-gram(1,6) : 0.7642648896293212
              precision    recall  f1-score   support

           0       0.72      0.85      0.78      1191
           1       0.82      0.68      0.74      1210

    accuracy                           0.76      2401
   macro avg       0.77      0.76      0.76      2401
weighted avg       0.77      0.76      0.76      2401

Best Parameters  {'multi_class': 'ovr', 'solver': 'saga'}
Best Score  0.7364285714285714
 
Confusion Matrix
[[1015  176]
 [ 390  820]]
 
Accuracy of Char n-gram(1,8) : 0.7805081216159934
              precision    recall  f1-score   support

           0       0.76      0.82      0.79      1191
           1       0.81      0.74      0.77      1210

    accuracy                           0.78      2401
   macro avg       0.78      0.78      0.78      2401
weighted avg       0.78      0.78      0.78      2401

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.784642857142

# Implementing Random Forest Classifier 

In [121]:
from sklearn.ensemble import RandomForestClassifier
RFC=RandomForestClassifier(n_estimators=13)
param={'n_estimators':[10, 20, 30]}
print("Random Forest Classifier")
w_rfc,c_rfc,wc_rfc=trainer(RFC,param, X, X_char, train, traintest, Y, y_test)

Random Forest Classifier
Accuracy of Word n-gram(1,6) : 0.7317784256559767
              precision    recall  f1-score   support

           0       0.70      0.86      0.77      1257
           1       0.79      0.59      0.68      1144

    accuracy                           0.73      2401
   macro avg       0.75      0.73      0.72      2401
weighted avg       0.74      0.73      0.73      2401

Best Parameters  {'n_estimators': 30}
Best Score  0.7317857142857143
 
Confusion Matrix
[[1082  175]
 [ 469  675]]
 
Accuracy of Char n-gram(1,8) : 0.7634319033735943
              precision    recall  f1-score   support

           0       0.75      0.83      0.79      1257
           1       0.78      0.69      0.74      1144

    accuracy                           0.76      2401
   macro avg       0.77      0.76      0.76      2401
weighted avg       0.77      0.76      0.76      2401

Best Parameters  {'n_estimators': 30}
Best Score  0.74625
 
Confusion Matrix
[[1039  218]
 [ 350  794]]


# Implementing Ensemble Hard voting


In [181]:
from sklearn.ensemble import VotingClassifier

In [182]:
vote_model = VotingClassifier(estimators=[('svcm', svc), ('MNBm', MNB), ('LRm', LR)], voting='hard')
param={}
w_ens,c_ens,wc_ens=trainer(vote_model,param, X, X_char, train, traintest, Y, y_test)

e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Word n-gram(1,6) : 0.7663473552686381
              precision    recall  f1-score   support

           0       0.71      0.90      0.79      1191
           1       0.87      0.63      0.73      1210

    accuracy                           0.77      2401
   macro avg       0.79      0.77      0.76      2401
weighted avg       0.79      0.77      0.76      2401

Best Parameters  {}
Best Score  0.7260714285714286
 
Confusion Matrix
[[1073  118]
 [ 443  767]]
 


e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Char n-gram(1,8) : 0.7721782590587255
              precision    recall  f1-score   support

           0       0.72      0.89      0.79      1191
           1       0.86      0.66      0.74      1210

    accuracy                           0.77      2401
   macro avg       0.79      0.77      0.77      2401
weighted avg       0.79      0.77      0.77      2401

Best Parameters  {}
Best Score  0.7764285714285715
 
Confusion Matrix
[[1059  132]
 [ 415  795]]
 


e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Combinining word & Char n-gram 0.7809246147438568
              precision    recall  f1-score   support

           0       0.73      0.90      0.80      1191
           1       0.87      0.67      0.75      1210

    accuracy                           0.78      2401
   macro avg       0.80      0.78      0.78      2401
weighted avg       0.80      0.78      0.78      2401

Best Parameters  {}
Best Score  0.7839285714285714
 
Confusion Matrix
[[1068  123]
 [ 403  807]]
 
