# importing necesary modeules

In [2]:
from sklearn.datasets import load_files
import pandas as pd

In [3]:
Mal_data=pd.read_excel("Malayalam_offensive_data_Training-YT.xlsx")

In [4]:
Mal_data[0:10]

ID                                             Tweets Labels
0  MA_YT001                   Thaankal enthaan cheyyarullath?😛    NOT
1  MA_YT002  Ee theetam WCC feminichigalude news aarkk vena...    OFF
2  MA_YT003  fukru nem tiktok oolakale vilich charcha nadat...    OFF
3  MA_YT004  Aashiq abu produce cheytharunnel ee problems u...    NOT
4  MA_YT005  Pennungal oru team aayal ath moonjum ennu epoo...    OFF
5  MA_YT006  @USER po oru Rajithakku parayam ennal oru Renj...    NOT
6  MA_YT007             @USER Ath kazhinju ulla sentence vayik    NOT
7  MA_YT008                        @USER TL vere oru ss kandu.    NOT
8  MA_YT009  @USER penninte peru paranj ,,,,soyam bodham po...    OFF
9  MA_YT010       @USER ninte chanthik ente vaka orayiram umma    OFF

# importing necesary modeules

In [11]:
import regex
import re
import numpy as np

In [12]:
labels,counts=np.unique(Mal_data['Labels'],return_counts=True)

In [13]:
print(labels,counts)

['NOT' 'OFF'] [2047 1953]


# storing tweets into msg. msg type is pandas series

In [14]:
msg=Mal_data['Tweets']

In [15]:
 type(msg), len(msg)

(pandas.core.series.Series, 4000)

# Removing all emojis from tweets by using the emojis code 

In [16]:
msg_emoj=msg.str.replace(r'[(\U0001F600-\U0001F92F|\U0001F300-\U0001F5FF|\U0001F680-\U0001F6FF|\U0001F190-\U0001F1FF|\U00002702-\U000027B0|\U0001F926-\U0001FA9F|\u200d|\u2640-\u2642|\u2600-\u2B55|\u23cf|\u23e9|\u231a|\ufe0f)]+','')

In [17]:
msg_emoj[10:20]

10               @USER aaano arinjilla..pavam femichees
11    @USER ningaldae oru avastha kashtam.... Sthret...
12    @USER Calicut ilas.. Athe enthina nadana nadan...
13    @USER ne oru kaaryma cheyy mohanlaline ninde a...
14    Nellarayude partner carrot um cucumber um thin...
15    @USER Nee ninte thallaye nattukarkk ookan kodu...
16           Gulfil minaral waterilano meen kazukaan ??
17    @USER thall illathe valarnna ninnod enth oaray...
18                            Businessil ithoke undakum
19    @USER njan oombumeda iniyum oombum ninne pole ...
Name: Tweets, dtype: object

# Removing @USER at the start of each tweet

In [18]:
msg_USER=msg_emoj.str.replace(r"@USER", '')
msg_USER[200:208]

200    kanapadham padhich parayuka aano answers...ee ...
201    Ee myrukal okke tiktokil kidann Enth myro kani...
202    Oroo oombiya videos ayitt eragikolum ... ee ku...
203    eyy Orikkalum Down akaruthu....video cheythond...
204                E patti theetathine kondano vannokane
205          Ivall athrekoo moshamaya kuttiyanoo😁😁
206                 Ithine follow cheyunore URL adikanam
207       Epo manasill ayyy real life koothare Annu Ennu
Name: Tweets, dtype: object

# Encoding  😁😁 & many other symbols to ASCII; so that those r removed from tweets. 
# After removal we can see msg is encoded and started with b'

In [19]:
msg_USER_Encod=msg_USER.str.encode("ascii", "ignore")
msg_USER_Encod[200:208], type(msg_USER_Encod)

(200    b'kanapadham padhich parayuka aano answers...e...
 201    b'Ee myrukal okke tiktokil kidann Enth myro ka...
 202    b'Oroo oombiya videos ayitt eragikolum ... ee ...
 203    b'eyy Orikkalum Down akaruthu....video cheytho...
 204             b'E patti theetathine kondano vannokane'
 205               b'Ivall athrekoo moshamaya kuttiyanoo'
 206              b'Ithine follow cheyunore URL adikanam'
 207    b'Epo manasill ayyy real life koothare Annu Ennu'
 Name: Tweets, dtype: object, pandas.core.series.Series)

# Decoding msg to format where we can see b' is removed 

In [20]:
msg_USER_decod=msg_USER_Encod.str.decode(encoding = 'ASCII')

In [21]:
    msg_USER_decod[0:10]

0                      Thaankal enthaan cheyyarullath?
1    Ee theetam WCC feminichigalude news aarkk vena...
2    fukru nem tiktok oolakale vilich charcha nadat...
3    Aashiq abu produce cheytharunnel ee problems u...
4    Pennungal oru team aayal ath moonjum ennu epoo...
5     po oru Rajithakku parayam ennal oru Renjithin...
6                     Ath kazhinju ulla sentence vayik
7                                TL vere oru ss kandu.
8     penninte peru paranj ,,,,soyam bodham polumil...
9               ninte chanthik ente vaka orayiram umma
Name: Tweets, dtype: object

# Removing digits 

In [22]:
msg_Digit = msg_USER_decod.str.replace(r'[0-9]', ' ')

In [23]:
msg_Digit[229:235]

229      Ee vanathine pokki adikkatha Vittiliri my..... 
230      :   Vttu kalayan ayitt .........{Vali} ond o...
231                    Awooo .bayangara veetukare thanne
232    Bhagavanee ithinum interviewvo ? Negative publ...
233    Pottanmar interview cheyan helen of spartayude...
234    Njn oru subscriber ayirunnu ee video kandappo ...
Name: Tweets, dtype: object

# Removing Special Characters

In [24]:
msg_SpChar = msg_Digit.str.replace(r'[^\w\d\s]', ' ')

In [25]:
msg_SpChar[229:235]

229      Ee vanathine pokki adikkatha Vittiliri my      
230          Vttu kalayan ayitt           Vali  ond o...
231                    Awooo  bayangara veetukare thanne
232    Bhagavanee ithinum interviewvo   Negative publ...
233    Pottanmar interview cheyan helen of spartayude...
234    Njn oru subscriber ayirunnu ee video kandappo ...
Name: Tweets, dtype: object

# Removing  Hyphens & xtra Whitespaces 

In [26]:
msg_Spac = msg_SpChar.str.replace(r'\s+', ' ')

In [27]:
msg_Hyp = msg_Spac.str.replace(r'_','')

In [28]:
msg_Hyp[229:235]

229           Ee vanathine pokki adikkatha Vittiliri my 
230        Vttu kalayan ayitt Vali ond onnu podi avdanu 
231                     Awooo bayangara veetukare thanne
232    Bhagavanee ithinum interviewvo Negative public...
233    Pottanmar interview cheyan helen of spartayude...
234    Njn oru subscriber ayirunnu ee video kandappo ...
Name: Tweets, dtype: object

# storing msg_spec (i.e. processed data) into dataframe Msg_df

In [29]:
Msg_df=pd.DataFrame(msg_Hyp)
Msg_df.columns=['Msg_with_Stopwords']

# Removing Null values 

In [30]:
Msg_df['Msg_with_Stopwords']=Msg_df['Msg_with_Stopwords'].fillna("")

In [31]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Removing Stop words 

In [32]:
stop_words = set(stopwords.words('english'))

In [33]:
Msg_df['Msg_without_Stopwords']=Msg_df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

# Counting length of each tweet for with stopwords and without stopwords & placing into dataframe : Msg_df

In [34]:
Msg_df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_with_Stopwords'].tolist()]
Msg_df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_without_Stopwords'].tolist()]

In [35]:
    Msg_df[228:231]

Msg_with_Stopwords  \
228    Aa committed aaya vaikthikku aadhranjalikal    
229      Ee vanathine pokki adikkatha Vittiliri my    
230   Vttu kalayan ayitt Vali ond onnu podi avdanu    

                            Msg_without_Stopwords  Msg_with_Stopwords_Len  \
228   Aa committed aaya vaikthikku aadhranjalikal                       5   
229        Ee vanathine pokki adikkatha Vittiliri                       6   
230  Vttu kalayan ayitt Vali ond onnu podi avdanu                       8   

     Msg_without_Stopwords_Len  
228                          5  
229                          5  
230                          8

# Counting Vowels and Consonents from each tweet

In [36]:
Msg_df['Vowels'] = Msg_df['Msg_without_Stopwords'].str.lower().str.count(r'[aeiou]')
Msg_df['Consonant'] = Msg_df['Msg_without_Stopwords'].str.lower().str.count(r'[a-z]') - Msg_df['Vowels']

In [37]:
Msg_df

Msg_with_Stopwords  \
0                       Thaankal enthaan cheyyarullath    
1     Ee theetam WCC feminichigalude news aarkk vena...   
2     fukru nem tiktok oolakale vilich charcha nadat...   
3     Aashiq abu produce cheytharunnel ee problems u...   
4     Pennungal oru team aayal ath moonjum ennu epoo...   
...                                                 ...   
3995  Eee parasayam thanne thettanu Ella achanmaraya...   
3996  Ente bagathum thetundh ee vazhikke veraan paad...   
3997  Kuttiye njan kettikolaam swarnam onnum venda e...   
3998  Chumma veettil irunna chakkiye trollanmaarkku ...   
3999                Kalidasan nalla look aayallo kanan    

                                  Msg_without_Stopwords  \
0                        Thaankal enthaan cheyyarullath   
1     Ee theetam WCC feminichigalude news aarkk vena...   
2     fukru nem tiktok oolakale vilich charcha nadat...   
3     Aashiq abu produce cheytharunnel ee problems u...   
4     Pennungal oru team aayal ath moonjum ennu epoo...   
...                                                 ...   
3995  Eee parasayam thanne thettanu Ella achanmaraya...   
3996  Ente bagathum thetundh ee vazhikke veraan paad...   
3997  Kuttiye njan kettikolaam swarnam onnum venda e...   
3998  Chumma veettil irunna chakkiye trollanmaarkku ...   
3999                 Kalidasan nalla look aayallo kanan   

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  Vowels  Consonant  
0                          3                          3      10         18  
1                          8                          8      21         29  
2                          9                          9      24         35  
3                          7                          7      22         31  
4                          9                          9      24         27  
...                      ...                        ...     ...        ...  
3995                      20                         20      67         89  
3996                       7                          7      21         26  
3997                      12                         12      29         44  
3998                      12                         12      37         45  
3999                       5                          5      14         16  

[4000 rows x 6 columns]

In [38]:
type(Mal_data),type(Msg_df)

(pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)

# Concatinating original dataframe i.e. Mal_data and modified dataframes i.e. Msg_df into final_Data

In [39]:
final_Data=pd.concat([Msg_df, Mal_data], axis=1)

In [40]:
final_Data[21:30]

Msg_with_Stopwords  \
21   ninte thanthakk andikk urappillathath kondall...   
22   ninde thallede number onnu theruo ante pattik...   
23   nintammene kootit ingot va Ennit ne maari nik...   
24      poda venne amma thooriyapoo therich poyavane    
25   nee ninte thallayod thanthayod para Closet va...   
26  Edo parvathi padmapriya onnum alla aaa revathi...   
27  Nadi mare nadimare ennalathr gusthikar ennu pa...   
28                          njan ninne sex cheythotte   
29                ithil ipo mindan vendum ntha undaye   

                                Msg_without_Stopwords  Msg_with_Stopwords_Len  \
21  ninte thanthakk andikk urappillathath kondalle...                      52   
22  ninde thallede number onnu theruo ante pattik ...                      21   
23  nintammene kootit ingot va Ennit ne maari nikk...                      30   
24       poda venne amma thooriyapoo therich poyavane                       6   
25  nee ninte thallayod thanthayod para Closet vaname                       7   
26  Edo parvathi padmapriya onnum alla aaa revathi...                      19   
27  Nadi mare nadimare ennalathr gusthikar ennu pa...                       8   
28                          njan ninne sex cheythotte                       4   
29                ithil ipo mindan vendum ntha undaye                       6   

    Msg_without_Stopwords_Len  Vowels  Consonant        ID  \
21                         49     126        200  MA_YT022   
22                         21      52         75  MA_YT023   
23                         30      73        111  MA_YT024   
24                          6      18         21  MA_YT025   
25                          7      17         26  MA_YT026   
26                         19      50         66  MA_YT027   
27                          8      22         30  MA_YT028   
28                          4       7         15  MA_YT029   
29                          6      12         18  MA_YT030   

                                               Tweets Labels  
21  @USER ninte thanthakk andikk urappillathath ko...    OFF  
22  @USER ninde thallede number onnu theruo...ante...    OFF  
23  @USER nintammene kootit ingot va. Ennit ne maa...    OFF  
24  @USER poda venne...🥰 amma thooriyapoo therich ...    OFF  
25  @USER nee ninte thallayod thanthayod para Clos...    OFF  
26  Edo parvathi padmapriya onnum alla aaa revathi...    OFF  
27  Nadi mare nadimare ennalathr gusthikar ennu pa...    NOT  
28                    @USER njan ninne sex cheythotte    OFF  
29          @USER ithil ipo mindan vendum ntha undaye    NOT

# Encoding the labels Offensive as 1 & NOT offensive as 0

In [41]:
final_Data['NLabels']=final_Data['Labels'].apply(lambda x: 1 if x=='OFF' else 0 )

# Dropping the columns Tweets, Labels and ID

In [42]:
final_Data=final_Data.drop(['Tweets', 'Labels', 'ID'], axis=1)

# Showing the Dataframe : final_Data

In [43]:
final_Data

Msg_with_Stopwords  \
0                       Thaankal enthaan cheyyarullath    
1     Ee theetam WCC feminichigalude news aarkk vena...   
2     fukru nem tiktok oolakale vilich charcha nadat...   
3     Aashiq abu produce cheytharunnel ee problems u...   
4     Pennungal oru team aayal ath moonjum ennu epoo...   
...                                                 ...   
3995  Eee parasayam thanne thettanu Ella achanmaraya...   
3996  Ente bagathum thetundh ee vazhikke veraan paad...   
3997  Kuttiye njan kettikolaam swarnam onnum venda e...   
3998  Chumma veettil irunna chakkiye trollanmaarkku ...   
3999                Kalidasan nalla look aayallo kanan    

                                  Msg_without_Stopwords  \
0                        Thaankal enthaan cheyyarullath   
1     Ee theetam WCC feminichigalude news aarkk vena...   
2     fukru nem tiktok oolakale vilich charcha nadat...   
3     Aashiq abu produce cheytharunnel ee problems u...   
4     Pennungal oru team aayal ath moonjum ennu epoo...   
...                                                 ...   
3995  Eee parasayam thanne thettanu Ella achanmaraya...   
3996  Ente bagathum thetundh ee vazhikke veraan paad...   
3997  Kuttiye njan kettikolaam swarnam onnum venda e...   
3998  Chumma veettil irunna chakkiye trollanmaarkku ...   
3999                 Kalidasan nalla look aayallo kanan   

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  Vowels  Consonant  \
0                          3                          3      10         18   
1                          8                          8      21         29   
2                          9                          9      24         35   
3                          7                          7      22         31   
4                          9                          9      24         27   
...                      ...                        ...     ...        ...   
3995                      20                         20      67         89   
3996                       7                          7      21         26   
3997                      12                         12      29         44   
3998                      12                         12      37         45   
3999                       5                          5      14         16   

      NLabels  
0           0  
1           1  
2           1  
3           0  
4           1  
...       ...  
3995        0  
3996        0  
3997        0  
3998        0  
3999        0  

[4000 rows x 7 columns]

In [47]:
final_Data['Msg_without_Stopwords']

0                          Thaankal enthaan cheyyarullath
1       Ee theetam WCC feminichigalude news aarkk vena...
2       fukru nem tiktok oolakale vilich charcha nadat...
3       Aashiq abu produce cheytharunnel ee problems u...
4       Pennungal oru team aayal ath moonjum ennu epoo...
                              ...                        
3995    Eee parasayam thanne thettanu Ella achanmaraya...
3996    Ente bagathum thetundh ee vazhikke veraan paad...
3997    Kuttiye njan kettikolaam swarnam onnum venda e...
3998    Chumma veettil irunna chakkiye trollanmaarkku ...
3999                   Kalidasan nalla look aayallo kanan
Name: Msg_without_Stopwords, Length: 4000, dtype: object

# splitting the dataset into train=70% & test=30% where X=final_Data.Msg_without_Stopwords & Y=final_Data.NLabels

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(final_Data.Msg_without_Stopwords, final_Data.NLabels,  random_state=40, test_size=0.3)

In [49]:
len(X_train), len(y_train), len(X_test), len(y_test)

(2800, 2800, 1200, 1200)

# Transforming the X_train using TF_IDF Vectorizer where dataset is lowercased; analyzer as word & n-gram as unigram

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(analyzer='word', lowercase=True , ngram_range=(1, 2))
X=tfidf.fit_transform(X_train) 
Y=y_train
tfidf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [51]:
char_tfidf=TfidfVectorizer(analyzer='char', lowercase=True, ngram_range=(1, 5))
X_char=char_tfidf.fit_transform(X_train) 
char_tfidf

TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 5), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

#  tfidf word  n-gram(1,2) extracted : features  = 38536
#  tfidf char  n-gram(1,5) extracted : features  = 81191


In [52]:
tfidf.get_feature_names()

['aa',
 'aa aala',
 'aa accountinte',
 'aa adikkan',
 'aa adisthanathil',
 'aa al',
 'aa amma',
 'aa bagyavan',
 'aa basheerine',
 'aa bedinadiyale',
 'aa beef',
 'aa casaba',
 'aa chekkanitta',
 'aa cinema',
 'aa collegl',
 'aa coment',
 'aa duplicate',
 'aa ellam',
 'aa film',
 'aa indarw',
 'aa instrument',
 'aa ishtam',
 'aa kannil',
 'aa karumbi',
 'aa kochine',
 'aa kunji',
 'aa kunjine',
 'aa kuttikalude',
 'aa kutty',
 'aa kuttykal',
 'aa kuttykalude',
 'aa manasu',
 'aa mathathile',
 'aa mic',
 'aa monjathiye',
 'aa moonjiya',
 'aa moviyil',
 'aa mugathu',
 'aa naarikal',
 'aa nariye',
 'aa news',
 'aa odukathe',
 'aa oola',
 'aa oru',
 'aa oula',
 'aa paisakku',
 'aa panna',
 'aa parasyathilu',
 'aa pattam',
 'aa pavam',
 'aa pavathinu',
 'aa payyan',
 'aa peedakaneyanu',
 'aa penkuttikk',
 'aa penkuttiye',
 'aa poorathiyude',
 'aa poorinoodu',
 'aa poorinte',
 'aa positionil',
 'aa pretham',
 'aa respect',
 'aa saidil',
 'aa samayathokke',
 'aa samsarashailyil',
 'aa samsara

In [53]:
char_tfidf.get_feature_names()

[' ',
 ' a',
 ' a ',
 ' a c',
 ' a ch',
 ' a e',
 ' a en',
 ' aa',
 ' aa ',
 ' aa a',
 ' aa b',
 ' aa c',
 ' aa d',
 ' aa e',
 ' aa f',
 ' aa i',
 ' aa k',
 ' aa m',
 ' aa n',
 ' aa o',
 ' aa p',
 ' aa r',
 ' aa s',
 ' aa t',
 ' aa v',
 ' aaa',
 ' aaa ',
 ' aaaa',
 ' aaad',
 ' aaah',
 ' aaak',
 ' aaal',
 ' aaan',
 ' aaar',
 ' aaay',
 ' aab',
 ' aaba',
 ' aac',
 ' aach',
 ' aad',
 ' aada',
 ' aadh',
 ' aadi',
 ' aado',
 ' aady',
 ' aag',
 ' aagr',
 ' aagu',
 ' aah',
 ' aah ',
 ' aahd',
 ' aahn',
 ' aai',
 ' aai ',
 ' aail',
 ' aair',
 ' aait',
 ' aaj',
 ' aaja',
 ' aak',
 ' aaka',
 ' aakh',
 ' aaki',
 ' aakk',
 ' aakm',
 ' aakr',
 ' aaks',
 ' aakt',
 ' aaku',
 ' aal',
 ' aal ',
 ' aala',
 ' aald',
 ' aale',
 ' aalk',
 ' aall',
 ' aalo',
 ' aalu',
 ' aam',
 ' aam ',
 ' aan',
 ' aan ',
 ' aana',
 ' aane',
 ' aank',
 ' aann',
 ' aano',
 ' aanp',
 ' aanu',
 ' aap',
 ' aapo',
 ' aar',
 ' aara',
 ' aare',
 ' aari',
 ' aark',
 ' aarn',
 ' aaro',
 ' aarr',
 ' aart',
 ' aaru',
 ' aas',
 ' aasa',

In [54]:
len(tfidf.vocabulary_), len(char_tfidf.vocabulary_), len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())

(38536, 81191, 38536, 81191)

In [55]:
X, X_char

(<2800x38536 sparse matrix of type '<class 'numpy.float64'>'
 	with 51651 stored elements in Compressed Sparse Row format>,
 <2800x81191 sparse matrix of type '<class 'numpy.float64'>'
 	with 762508 stored elements in Compressed Sparse Row format>)

In [56]:
from scipy.sparse import hstack
train=hstack([X,X_char])
train

<2800x119727 sparse matrix of type '<class 'numpy.float64'>'
	with 814159 stored elements in COOrdinate format>

In [57]:
Xt=tfidf.transform(X_test) 
Xt_char=char_tfidf.transform(X_test) 

In [58]:
Xt, Xt_char

(<1200x38536 sparse matrix of type '<class 'numpy.float64'>'
 	with 7105 stored elements in Compressed Sparse Row format>,
 <1200x81191 sparse matrix of type '<class 'numpy.float64'>'
 	with 303257 stored elements in Compressed Sparse Row format>)

In [59]:
traintest=hstack([Xt,Xt_char])
traintest

<1200x119727 sparse matrix of type '<class 'numpy.float64'>'
	with 310362 stored elements in COOrdinate format>

In [60]:
mal_hasoc=pd.read_excel("malayalam_hasoc_tanglish_test_without_labels.xlsx", header=None)
mal_hasoc=mal_hasoc.rename(columns={0:'ID', 1:'Tweets'})
test_Mal_Hasoc=mal_hasoc['Tweets']

test_Mal_Hasoc_word=tfidf.transform(test_Mal_Hasoc)
test_Mal_Hasoc_char=char_tfidf.transform(test_Mal_Hasoc)
test_Mal_Hasoc_word_char=hstack([test_Mal_Hasoc_word,test_Mal_Hasoc_char])

In [61]:
test_Mal_Hasoc_word, test_Mal_Hasoc_char, test_Mal_Hasoc_word_char

(<1000x38536 sparse matrix of type '<class 'numpy.float64'>'
 	with 5556 stored elements in Compressed Sparse Row format>,
 <1000x81191 sparse matrix of type '<class 'numpy.float64'>'
 	with 260748 stored elements in Compressed Sparse Row format>,
 <1000x119727 sparse matrix of type '<class 'numpy.float64'>'
 	with 266304 stored elements in COOrdinate format>)

In [62]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score, f1_score 

In [63]:
def trainer(model_obj, param, X, X_char, train, traintest, Y, y_test):
    
    GSCV=GridSearchCV(model_obj, param , return_train_score=False)
    GSCV.fit(X,Y)
    #Training Classifier with TF-IDF Features Word n-gram
    #model_obj.fit(X,Y)
    print("Accuracy of Word n-gram(1,2) :", (GSCV.score(tfidf.transform(X_test), y_test)))
    #Printing Classification Report
    predict=GSCV.predict(Xt)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=GSCV.predict(test_Mal_Hasoc_word)
    
    pre=precision_score(y_test, predict)
    rec=recall_score(y_test, predict)
    f1s=f1_score(y_test, predict)
    
    print("Precision : ", pre)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)

  #Training Classifier with TF-IDF Features Char n-gram
    GSCV.fit(X_char, Y)
    print("Accuracy of Char n-gram(1,5) :", (GSCV.score(char_tfidf.transform(X_test), y_test)))
    predict=GSCV.predict(Xt_char)
    print(classification_report(y_test, predict))
   #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=GSCV.predict(test_Mal_Hasoc_char)
    
    pre=precision_score(y_test, predict)
    rec=recall_score(y_test, predict)
    f1s=f1_score(y_test, predict)
    
    print("Precision : ", pre)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)
        
              
    #Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    GSCV.fit(train, Y)
    print("Accuracy of Combinining word & Char n-gram", (GSCV.score(traintest, y_test)))
    #Printing Classification Report
    predict=GSCV.predict(traintest)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=GSCV.predict(test_Mal_Hasoc_word_char)
    
    pre=precision_score(y_test, predict)
    rec=recall_score(y_test, predict)
    f1s=f1_score(y_test, predict)
    
    print("Precision : ", pre)
    print("Recall : ", rec)
    print("F1 Score : ", f1s)

    
    return word, char, word_char

# Implementing SVC

In [53]:
from sklearn.svm import SVC
svc=SVC()
print("SVC")
param={'kernel':('linear', 'rbf'), 'gamma':('auto', 'scale'), 'C':[0.9, 10, 20, 30]}
w_svc,c_svc,wc_svc=trainer(svc,param, X, X_char, train, traintest, Y, y_test)

SVC
Accuracy of Word n-gram(1,2) : 0.71
              precision    recall  f1-score   support

           0       0.70      0.78      0.74       624
           1       0.72      0.64      0.68       576

    accuracy                           0.71      1200
   macro avg       0.71      0.71      0.71      1200
weighted avg       0.71      0.71      0.71      1200

Best Parameters  {'C': 0.9, 'gamma': 'auto', 'kernel': 'linear'}
Best Score  0.6778571428571428
 
Confusion Matrix
[[484 140]
 [208 368]]
 
Accuracy of Char n-gram(1,5) : 0.7466666666666667
              precision    recall  f1-score   support

           0       0.74      0.80      0.77       624
           1       0.76      0.69      0.72       576

    accuracy                           0.75      1200
   macro avg       0.75      0.74      0.74      1200
weighted avg       0.75      0.75      0.75      1200

Best Parameters  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Best Score  0.7321428571428571
 
Confusion Matrix
[[50

In [55]:
w_svc=pd.DataFrame(w_svc, columns=["Word_SVC"])
c_svc=pd.DataFrame(c_svc, columns=["Char_SVC"])
wc_svc=pd.DataFrame(wc_svc, columns=["Combine Word Char_SVC"])
res_svm=pd.concat([w_svc,c_svc,wc_svc], axis=1)
res_svm

Word_SVC  Char_SVC  Combine Word Char_SVC
0           0         0                      0
1           0         0                      0
2           0         0                      0
3           0         0                      0
4           0         0                      0
..        ...       ...                    ...
995         1         0                      1
996         0         0                      0
997         1         1                      1
998         0         0                      0
999         0         1                      1

[1000 rows x 3 columns]

# Implementing Multinomial Naive Bayes 

In [64]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB(alpha=2.0)
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train, traintest, Y, y_test)

Multi Nominal Bayes
Accuracy of Word n-gram(1,2) : 0.7133333333333334
              precision    recall  f1-score   support

           0       0.70      0.79      0.74       624
           1       0.73      0.63      0.68       576

    accuracy                           0.71      1200
   macro avg       0.72      0.71      0.71      1200
weighted avg       0.72      0.71      0.71      1200

Best Parameters  {'alpha': 0.7}
Best Score  0.6889285714285714
 
Confusion Matrix
[[491 133]
 [211 365]]
 
Precision :  0.7329317269076305
Recall :  0.6336805555555556
F1 Score :  0.6797020484171322
Accuracy of Char n-gram(1,5) : 0.7366666666666667
              precision    recall  f1-score   support

           0       0.74      0.77      0.75       624
           1       0.74      0.70      0.72       576

    accuracy                           0.74      1200
   macro avg       0.74      0.74      0.74      1200
weighted avg       0.74      0.74      0.74      1200

Best Parameters  {'alpha': 

In [57]:
w_mnb=pd.DataFrame(w_mnb, columns=["Word_MNB"])
c_mnb=pd.DataFrame(c_mnb, columns=["Char_MNB"])
wc_mnb=pd.DataFrame(wc_mnb, columns=["Combine Word Char_MNB"])
res_mnb=pd.concat([w_mnb,c_mnb,wc_mnb], axis=1)
res_mnb

Word_MNB  Char_MNB  Combine Word Char_MNB
0           0         0                      0
1           0         0                      0
2           0         0                      0
3           0         0                      0
4           1         1                      1
..        ...       ...                    ...
995         1         1                      1
996         0         0                      0
997         1         1                      1
998         0         0                      0
999         0         1                      1

[1000 rows x 3 columns]

# Implementing Logistic Regression 

In [69]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(random_state=40, solver='lbfgs')
param={'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'), 'multi_class':('ovr', 'auto')}
print("Logisitc Regression")
w_lr,c_lr,wc_lr=trainer(LR,param, X, X_char, train, traintest, Y, y_test)

Logisitc Regression
Accuracy of Word n-gram(1,2) : 0.6966666666666667
              precision    recall  f1-score   support

           0       0.68      0.79      0.73       624
           1       0.72      0.60      0.65       576

    accuracy                           0.70      1200
   macro avg       0.70      0.69      0.69      1200
weighted avg       0.70      0.70      0.69      1200

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.6792857142857143
 
Confusion Matrix
[[492 132]
 [232 344]]
 
Precision :  0.7226890756302521
Recall :  0.5972222222222222
F1 Score :  0.6539923954372623


e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Accuracy of Char n-gram(1,5) : 0.7375
              precision    recall  f1-score   support

           0       0.73      0.79      0.76       624
           1       0.75      0.68      0.71       576

    accuracy                           0.74      1200
   macro avg       0.74      0.74      0.74      1200
weighted avg       0.74      0.74      0.74      1200

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.7242857142857143
 
Confusion Matrix
[[496 128]
 [187 389]]
 
Precision :  0.7524177949709865
Recall :  0.6753472222222222
F1 Score :  0.7118023787740165


e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Accuracy of Combinining word & Char n-gram 0.745
              precision    recall  f1-score   support

           0       0.73      0.80      0.77       624
           1       0.76      0.68      0.72       576

    accuracy                           0.74      1200
   macro avg       0.75      0.74      0.74      1200
weighted avg       0.75      0.74      0.74      1200

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.7314285714285714
 
Confusion Matrix
[[501 123]
 [183 393]]
 
Precision :  0.7616279069767442
Recall :  0.6822916666666666
F1 Score :  0.7197802197802198


In [59]:
w_lr=pd.DataFrame(w_lr, columns=["Word_LR"])
c_lr=pd.DataFrame(c_lr, columns=["Char_LR"])
wc_lr=pd.DataFrame(wc_lr, columns=["Combine Word Char_LR"])
res_lr=pd.concat([w_lr,c_lr,wc_lr], axis=1)
res_lr

Word_LR  Char_LR  Combine Word Char_LR
0          0        0                     0
1          0        0                     0
2          0        0                     0
3          0        0                     0
4          0        0                     0
..       ...      ...                   ...
995        1        0                     1
996        0        0                     0
997        1        1                     1
998        0        0                     0
999        0        1                     1

[1000 rows x 3 columns]

# Implementing Random Forest Classifier

In [70]:
from sklearn.ensemble import RandomForestClassifier
RFC=RandomForestClassifier(n_estimators=13)
param={'n_estimators':[10, 20, 30]}
print("Random Forest Classifier")
w_rfc,c_rfc,wc_rfc=trainer(RFC,param, X, X_char, train, traintest, Y, y_test)

Random Forest Classifier
Accuracy of Word n-gram(1,2) : 0.6541666666666667
              precision    recall  f1-score   support

           0       0.63      0.79      0.70       624
           1       0.69      0.51      0.59       576

    accuracy                           0.65      1200
   macro avg       0.66      0.65      0.64      1200
weighted avg       0.66      0.65      0.65      1200

Best Parameters  {'n_estimators': 20}
Best Score  0.6328571428571429
 
Confusion Matrix
[[492 132]
 [283 293]]
 
Precision :  0.6894117647058824
Recall :  0.5086805555555556
F1 Score :  0.5854145854145855
Accuracy of Char n-gram(1,5) : 0.6908333333333333
              precision    recall  f1-score   support

           0       0.68      0.78      0.72       624
           1       0.71      0.60      0.65       576

    accuracy                           0.69      1200
   macro avg       0.69      0.69      0.69      1200
weighted avg       0.69      0.69      0.69      1200

Best Parameters 

In [61]:
w_rfc=pd.DataFrame(w_rfc, columns=["Word_RFC"])
c_rfc=pd.DataFrame(c_rfc, columns=["Char_RFC"])
wc_rfc=pd.DataFrame(wc_rfc, columns=["Combine Word Char_RFC"])
res_rfc=pd.concat([w_rfc,c_rfc,wc_rfc], axis=1)
res_rfc

Word_RFC  Char_RFC  Combine Word Char_RFC
0           0         0                      0
1           0         0                      1
2           0         0                      1
3           0         0                      0
4           0         0                      0
..        ...       ...                    ...
995         1         1                      1
996         0         0                      0
997         1         1                      1
998         0         0                      0
999         0         0                      0

[1000 rows x 3 columns]

# Implementing DecisionTreeClassifier 


In [62]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier()
param={'criterion':('entropy', 'gini')}
print("Decision Tree Classifier")
w_dtc,c_dtc,wc_dtc=trainer(DTC,param, X, X_char, train, traintest, Y, y_test)

Decision Tree Classifier
Accuracy of Word n-gram(1,2) : 0.5925
              precision    recall  f1-score   support

           0       0.62      0.55      0.58       624
           1       0.57      0.64      0.60       576

    accuracy                           0.59      1200
   macro avg       0.59      0.59      0.59      1200
weighted avg       0.60      0.59      0.59      1200

Best Parameters  {'criterion': 'gini'}
Best Score  0.6025
 
Confusion Matrix
[[344 280]
 [209 367]]
 
Accuracy of Char n-gram(1,5) : 0.6291666666666667
              precision    recall  f1-score   support

           0       0.65      0.63      0.64       624
           1       0.61      0.63      0.62       576

    accuracy                           0.63      1200
   macro avg       0.63      0.63      0.63      1200
weighted avg       0.63      0.63      0.63      1200

Best Parameters  {'criterion': 'entropy'}
Best Score  0.6246428571428572
 
Confusion Matrix
[[392 232]
 [213 363]]
 
Accuracy of Co

In [63]:
w_dtc=pd.DataFrame(w_dtc, columns=["Word_DTC"])
c_dtc=pd.DataFrame(c_dtc, columns=["Char_DTC"])
wc_dtc=pd.DataFrame(wc_dtc, columns=["Combine Word Char_DTC"])
res_dtc=pd.concat([w_dtc,c_dtc,wc_dtc], axis=1)
res_dtc

Word_DTC  Char_DTC  Combine Word Char_DTC
0           0         0                      1
1           0         0                      0
2           0         1                      1
3           0         0                      0
4           0         0                      0
..        ...       ...                    ...
995         1         1                      1
996         0         0                      0
997         1         1                      1
998         0         0                      0
999         0         0                      0

[1000 rows x 3 columns]

# Implementing AdaBoost 

In [64]:
from sklearn.ensemble import AdaBoostClassifier
ABC=AdaBoostClassifier()
print("AdaBoost Classifier")
param={'n_estimators':[100, 200, 250, 300]}
w_abc,c_abc,wc_abc=trainer(ABC,param, X, X_char, train, traintest, Y, y_test)

AdaBoost Classifier
Accuracy of Word n-gram(1,2) : 0.6566666666666666
              precision    recall  f1-score   support

           0       0.63      0.84      0.72       624
           1       0.73      0.45      0.56       576

    accuracy                           0.66      1200
   macro avg       0.68      0.65      0.64      1200
weighted avg       0.68      0.66      0.64      1200

Best Parameters  {'n_estimators': 300}
Best Score  0.6192857142857143
 
Confusion Matrix
[[527  97]
 [315 261]]
 
Accuracy of Char n-gram(1,5) : 0.6666666666666666
              precision    recall  f1-score   support

           0       0.67      0.72      0.69       624
           1       0.67      0.61      0.64       576

    accuracy                           0.67      1200
   macro avg       0.67      0.66      0.66      1200
weighted avg       0.67      0.67      0.67      1200

Best Parameters  {'n_estimators': 100}
Best Score  0.685
 
Confusion Matrix
[[448 176]
 [224 352]]
 
Accuracy of

In [66]:
w_abc=pd.DataFrame(w_abc, columns=["Word_ABC"])
c_abc=pd.DataFrame(c_abc, columns=["Char_ABC"])
wc_abc=pd.DataFrame(wc_abc, columns=["Combine Word Char_ABC"])
res_abc=pd.concat([w_abc,c_abc,wc_abc], axis=1)
res_abc

Word_ABC  Char_ABC  Combine Word Char_ABC
0           0         0                      0
1           0         0                      0
2           0         1                      1
3           0         1                      0
4           0         0                      0
..        ...       ...                    ...
995         1         1                      1
996         0         0                      1
997         1         1                      1
998         0         0                      0
999         0         0                      1

[1000 rows x 3 columns]

#   Ensemble Approch: max voting 

In [67]:
from sklearn.ensemble import VotingClassifier

In [68]:
vote_model = VotingClassifier(estimators=[('svcm', svc), ('MNBm', MNB), ('LRm', LR)], voting='hard')
param={}
w_ens,c_ens,wc_ens=trainer(vote_model,param, X, X_char, train, traintest, Y, y_test)

e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Word n-gram(1,2) : 0.7033333333333334
              precision    recall  f1-score   support

           0       0.67      0.83      0.74       624
           1       0.75      0.57      0.65       576

    accuracy                           0.70      1200
   macro avg       0.71      0.70      0.70      1200
weighted avg       0.71      0.70      0.70      1200

Best Parameters  {}
Best Score  0.6810714285714285
 
Confusion Matrix
[[517 107]
 [249 327]]
 


e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Char n-gram(1,5) : 0.7391666666666666
              precision    recall  f1-score   support

           0       0.71      0.83      0.77       624
           1       0.78      0.64      0.70       576

    accuracy                           0.74      1200
   macro avg       0.75      0.74      0.74      1200
weighted avg       0.74      0.74      0.74      1200

Best Parameters  {}
Best Score  0.7278571428571429
 
Confusion Matrix
[[518 106]
 [207 369]]
 


e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Combinining word & Char n-gram 0.7541666666666667
              precision    recall  f1-score   support

           0       0.73      0.85      0.78       624
           1       0.80      0.65      0.72       576

    accuracy                           0.75      1200
   macro avg       0.76      0.75      0.75      1200
weighted avg       0.76      0.75      0.75      1200

Best Parameters  {}
Best Score  0.7317857142857143
 
Confusion Matrix
[[530  94]
 [201 375]]
 


In [69]:
w_ens=pd.DataFrame(w_ens, columns=["Word_Ensem"])
c_ens=pd.DataFrame(c_ens, columns=["Char_Ensem"])
wc_ens=pd.DataFrame(wc_ens, columns=["Combine Word Char_Ensem"])
res_ens=pd.concat([w_ens,c_ens,wc_ens], axis=1)
res_ens

Word_Ensem  Char_Ensem  Combine Word Char_Ensem
0             0           0                        0
1             0           0                        0
2             0           0                        0
3             0           0                        0
4             0           0                        0
..          ...         ...                      ...
995           1           0                        1
996           0           0                        0
997           1           1                        1
998           0           0                        0
999           0           1                        1

[1000 rows x 3 columns]

In [70]:
FINAL=pd.concat([res_svm, res_mnb, res_lr, res_rfc, res_dtc, res_abc, res_ens], axis=1)

In [71]:
FINAL

Word_SVC  Char_SVC  Combine Word Char_SVC  Word_MNB  Char_MNB  \
0           0         0                      0         0         0   
1           0         0                      0         0         0   
2           0         0                      0         0         0   
3           0         0                      0         0         0   
4           0         0                      0         1         1   
..        ...       ...                    ...       ...       ...   
995         1         0                      1         1         1   
996         0         0                      0         0         0   
997         1         1                      1         1         1   
998         0         0                      0         0         0   
999         0         1                      1         0         1   

     Combine Word Char_MNB  Word_LR  Char_LR  Combine Word Char_LR  Word_RFC  \
0                        0        0        0                     0         0   
1                        0        0        0                     0         0   
2                        0        0        0                     0         0   
3                        0        0        0                     0         0   
4                        1        0        0                     0         0   
..                     ...      ...      ...                   ...       ...   
995                      1        1        0                     1         1   
996                      0        0        0                     0         0   
997                      1        1        1                     1         1   
998                      0        0        0                     0         0   
999                      1        0        1                     1         0   

     ...  Combine Word Char_RFC  Word_DTC  Char_DTC  Combine Word Char_DTC  \
0    ...                      0         0         0                      1   
1    ...                      1         0         0                      0   
2    ...                      1         0         1                      1   
3    ...                      0         0         0                      0   
4    ...                      0         0         0                      0   
..   ...                    ...       ...       ...                    ...   
995  ...                      1         1         1                      1   
996  ...                      0         0         0                      0   
997  ...                      1         1         1                      1   
998  ...                      0         0         0                      0   
999  ...                      0         0         0                      0   

     Word_ABC  Char_ABC  Combine Word Char_ABC  Word_Ensem  Char_Ensem  \
0           0         0                      0           0           0   
1           0         0                      0           0           0   
2           0         1                      1           0           0   
3           0         1                      0           0           0   
4           0         0                      0           0           0   
..        ...       ...                    ...         ...         ...   
995         1         1                      1           1           0   
996         0         0                      1           0           0   
997         1         1                      1           1           1   
998         0         0                      0           0           0   
999         0         0                      1           0           1   

     Combine Word Char_Ensem  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  
..                       ...  
995                        1  
996                        0  
997                        1  
998                        0  
999                        1  

[100

In [74]:
FINAL['Word_SVC'] = FINAL['Word_SVC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_SVC'] = FINAL['Char_SVC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_SVC']= FINAL['Combine Word Char_SVC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_MNB'] = FINAL['Word_MNB'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_MNB'] = FINAL['Char_MNB'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_MNB']= FINAL['Combine Word Char_MNB'].map({0 : 'NOT', 1 : 'OFF'})


FINAL['Word_LR'] = FINAL['Word_LR'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_LR'] = FINAL['Char_LR'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_LR']= FINAL['Combine Word Char_LR'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_RFC'] = FINAL['Word_RFC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_RFC'] = FINAL['Char_RFC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_RFC']= FINAL['Combine Word Char_RFC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_DTC'] = FINAL['Word_DTC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_DTC'] = FINAL['Char_DTC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_DTC']= FINAL['Combine Word Char_DTC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_ABC'] = FINAL['Word_ABC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_ABC'] = FINAL['Char_ABC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_ABC']= FINAL['Combine Word Char_ABC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_Ensem'] = FINAL['Word_Ensem'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_Ensem'] = FINAL['Char_Ensem'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_Ensem']= FINAL['Combine Word Char_Ensem'].map({0 : 'NOT', 1 : 'OFF'})

In [75]:
FINAL

Word_SVC Char_SVC Combine Word Char_SVC Word_MNB Char_MNB  \
0        NOT      NOT                   NOT      NOT      NOT   
1        NOT      NOT                   NOT      NOT      NOT   
2        NOT      NOT                   NOT      NOT      NOT   
3        NOT      NOT                   NOT      NOT      NOT   
4        NOT      NOT                   NOT      OFF      OFF   
..       ...      ...                   ...      ...      ...   
995      OFF      NOT                   OFF      OFF      OFF   
996      NOT      NOT                   NOT      NOT      NOT   
997      OFF      OFF                   OFF      OFF      OFF   
998      NOT      NOT                   NOT      NOT      NOT   
999      NOT      OFF                   OFF      NOT      OFF   

    Combine Word Char_MNB Word_LR Char_LR Combine Word Char_LR Word_RFC  ...  \
0                     NOT     NOT     NOT                  NOT      NOT  ...   
1                     NOT     NOT     NOT                  NOT      NOT  ...   
2                     NOT     NOT     NOT                  NOT      NOT  ...   
3                     NOT     NOT     NOT                  NOT      NOT  ...   
4                     OFF     NOT     NOT                  NOT      NOT  ...   
..                    ...     ...     ...                  ...      ...  ...   
995                   OFF     OFF     NOT                  OFF      OFF  ...   
996                   NOT     NOT     NOT                  NOT      NOT  ...   
997                   OFF     OFF     OFF                  OFF      OFF  ...   
998                   NOT     NOT     NOT                  NOT      NOT  ...   
999                   OFF     NOT     OFF                  OFF      NOT  ...   

    Combine Word Char_RFC Word_DTC Char_DTC Combine Word Char_DTC Word_ABC  \
0                     NOT      NOT      NOT                   OFF      NOT   
1                     OFF      NOT      NOT                   NOT      NOT   
2                     OFF      NOT      OFF                   OFF      NOT   
3                     NOT      NOT      NOT                   NOT      NOT   
4                     NOT      NOT      NOT                   NOT      NOT   
..                    ...      ...      ...                   ...      ...   
995                   OFF      OFF      OFF                   OFF      OFF   
996                   NOT      NOT      NOT                   NOT      NOT   
997                   OFF      OFF      OFF                   OFF      OFF   
998                   NOT      NOT      NOT                   NOT      NOT   
999                   NOT      NOT      NOT                   NOT      NOT   

    Char_ABC Combine Word Char_ABC Word_Ensem Char_Ensem  \
0        NOT                   NOT        NOT        NOT   
1        NOT                   NOT        NOT        NOT   
2        OFF                   OFF        NOT        NOT   
3        OFF                   NOT        NOT        NOT   
4        NOT                   NOT        NOT        NOT   
..       ...                   ...        ...        ...   
995      OFF                   OFF        OFF        NOT   
996      NOT                   OFF        NOT        NOT   
997      OFF                   OFF        OFF        OFF   
998      NOT                   NOT        NOT        NOT   
999      NOT                   OFF        NOT        OFF   

    Combine Word Char_Ensem  
0                       NOT  
1                       NOT  
2                       NOT  
3                       NOT  
4                       NOT  
..                      ...  
995                     OFF  
996                     NOT  
997                     OFF  
998                     NOT  
999                     OFF  

[1000 rows x 21 columns]

In [76]:
mal_hasoc1=pd.concat([mal_hasoc, FINAL], axis=1)

In [77]:
mal_hasoc1

ID                                             Tweets Word_SVC  \
0    MA_YT5000               Chenkol vendath thanne aayirunnu....      NOT   
1    MA_YT5001              Sundardasinte bhakshnam vakkukal ano?      NOT   
2    MA_YT5002  Akasha dooth oru copy adi movie anu 'Who will ...      NOT   
3    MA_YT5003  Purath onnum pondade... oru pennum payyanum on...      NOT   
4    MA_YT5004  Avasanam Fahad oru Oscar medikkumbazhum lalett...      NOT   
..         ...                                                ...      ...   
995  MA_YT5995  Njanum ee myran karanam sndpyil pravarthikkan ...      OFF   
996  MA_YT5996   allankil thanne malayalik enth kittiyalum mat...      NOT   
997  MA_YT5997  poda poora avante oru konavathiyaram....nee th...      OFF   
998  MA_YT5998  Satyam aaru paranjallum athu angikarikkana Man...      NOT   
999  MA_YT5999  Oru kudumbathinte kuthaka ennulla reethi maatt...      NOT   

    Char_SVC Combine Word Char_SVC Word_MNB Char_MNB Combine Word Char_MNB  \
0        NOT                   NOT      NOT      NOT                   NOT   
1        NOT                   NOT      NOT      NOT                   NOT   
2        NOT                   NOT      NOT      NOT                   NOT   
3        NOT                   NOT      NOT      NOT                   NOT   
4        NOT                   NOT      OFF      OFF                   OFF   
..       ...                   ...      ...      ...                   ...   
995      NOT                   OFF      OFF      OFF                   OFF   
996      NOT                   NOT      NOT      NOT                   NOT   
997      OFF                   OFF      OFF      OFF                   OFF   
998      NOT                   NOT      NOT      NOT                   NOT   
999      OFF                   OFF      NOT      OFF                   OFF   

    Word_LR Char_LR  ... Combine Word Char_RFC Word_DTC Char_DTC  \
0       NOT     NOT  ...                   NOT      NOT      NOT   
1       NOT     NOT  ...                   OFF      NOT      NOT   
2       NOT     NOT  ...                   OFF      NOT      OFF   
3       NOT     NOT  ...                   NOT      NOT      NOT   
4       NOT     NOT  ...                   NOT      NOT      NOT   
..      ...     ...  ...                   ...      ...      ...   
995     OFF     NOT  ...                   OFF      OFF      OFF   
996     NOT     NOT  ...                   NOT      NOT      NOT   
997     OFF     OFF  ...                   OFF      OFF      OFF   
998     NOT     NOT  ...                   NOT      NOT      NOT   
999     NOT     OFF  ...                   NOT      NOT      NOT   

    Combine Word Char_DTC Word_ABC Char_ABC Combine Word Char_ABC Word_Ensem  \
0                     OFF      NOT      NOT                   NOT        NOT   
1                     NOT      NOT      NOT                   NOT        NOT   
2                     OFF      NOT      OFF                   OFF        NOT   
3                     NOT      NOT      OFF                   NOT        NOT   
4                     NOT      NOT      NOT                   NOT        NOT   
..                    ...      ...      ...                   ...        ...   
995                   OFF      OFF      OFF                   OFF        OFF   
996                   NOT      NOT      NOT                   OFF        NOT   
997                   OFF      OFF      OFF                   OFF        OFF   
998                   NOT      NOT      NOT                   NOT        NOT   
999                   NOT      NOT      NOT                   OFF        NOT   

    Char_Ensem Combine Word Char_Ensem  
0          NOT                     NOT  
1          NOT                     NOT  
2          NOT                     NOT  
3          NOT                     NOT  
4          NOT                     NOT  
..         ...                     ...  
995        NOT                     OFF  
996        NOT                  

In [78]:
mal_hasoc1.to_csv("malayalam_hasoc_tanglish_test_with_labels.csv")

In [79]:
df1=pd.read_csv("malayalam_hasoc_tanglish_test_with_labels.csv")

In [80]:
df1

Unnamed: 0         ID                                             Tweets  \
0             0  MA_YT5000               Chenkol vendath thanne aayirunnu....   
1             1  MA_YT5001              Sundardasinte bhakshnam vakkukal ano?   
2             2  MA_YT5002  Akasha dooth oru copy adi movie anu 'Who will ...   
3             3  MA_YT5003  Purath onnum pondade... oru pennum payyanum on...   
4             4  MA_YT5004  Avasanam Fahad oru Oscar medikkumbazhum lalett...   
..          ...        ...                                                ...   
995         995  MA_YT5995  Njanum ee myran karanam sndpyil pravarthikkan ...   
996         996  MA_YT5996   allankil thanne malayalik enth kittiyalum mat...   
997         997  MA_YT5997  poda poora avante oru konavathiyaram....nee th...   
998         998  MA_YT5998  Satyam aaru paranjallum athu angikarikkana Man...   
999         999  MA_YT5999  Oru kudumbathinte kuthaka ennulla reethi maatt...   

    Word_SVC Char_SVC Combine Word Char_SVC Word_MNB Char_MNB  \
0        NOT      NOT                   NOT      NOT      NOT   
1        NOT      NOT                   NOT      NOT      NOT   
2        NOT      NOT                   NOT      NOT      NOT   
3        NOT      NOT                   NOT      NOT      NOT   
4        NOT      NOT                   NOT      OFF      OFF   
..       ...      ...                   ...      ...      ...   
995      OFF      NOT                   OFF      OFF      OFF   
996      NOT      NOT                   NOT      NOT      NOT   
997      OFF      OFF                   OFF      OFF      OFF   
998      NOT      NOT                   NOT      NOT      NOT   
999      NOT      OFF                   OFF      NOT      OFF   

    Combine Word Char_MNB Word_LR  ... Combine Word Char_RFC Word_DTC  \
0                     NOT     NOT  ...                   NOT      NOT   
1                     NOT     NOT  ...                   OFF      NOT   
2                     NOT     NOT  ...                   OFF      NOT   
3                     NOT     NOT  ...                   NOT      NOT   
4                     OFF     NOT  ...                   NOT      NOT   
..                    ...     ...  ...                   ...      ...   
995                   OFF     OFF  ...                   OFF      OFF   
996                   NOT     NOT  ...                   NOT      NOT   
997                   OFF     OFF  ...                   OFF      OFF   
998                   NOT     NOT  ...                   NOT      NOT   
999                   OFF     NOT  ...                   NOT      NOT   

    Char_DTC Combine Word Char_DTC Word_ABC Char_ABC Combine Word Char_ABC  \
0        NOT                   OFF      NOT      NOT                   NOT   
1        NOT                   NOT      NOT      NOT                   NOT   
2        OFF                   OFF      NOT      OFF                   OFF   
3        NOT                   NOT      NOT      OFF                   NOT   
4        NOT                   NOT      NOT      NOT                   NOT   
..       ...                   ...      ...      ...                   ...   
995      OFF                   OFF      OFF      OFF                   OFF   
996      NOT                   NOT      NOT      NOT                   OFF   
997      OFF                   OFF      OFF      OFF                   OFF   
998      NOT                   NOT      NOT      NOT                   NOT   
999      NOT                   NOT      NOT      NOT                   OFF   

    Word_Ensem Char_Ensem Combine Word Char_Ensem  
0          NOT        NOT                     NOT  
1          NOT        NOT                     NOT  
2          NOT        NOT                     NOT  
3          NOT        NOT                     NOT  
4          NOT        NOT                     NOT  
..         ...        ...                     ...  
995        OFF        NOT                     OFF  
996        NOT       

# Neural Network for Text Classification

In [65]:
import tensorflow as tf
from tensorflow import keras

from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

Using TensorFlow backend.


In [66]:
corpus=X_train
type(corpus), len(corpus)

(pandas.core.series.Series, 2800)

In [93]:
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)

In [94]:
len(all_words)

27823

In [95]:
# printing first tokenized words of corpus, so as to check wheteher last twwets has some words
all_words[:20]

['Ithanu',
 'marunada',
 'Chinayile',
 'communist',
 'soshiyalisam',
 'rajavu',
 'nagnananu',
 'Jismitha',
 'N',
 'ninne',
 'njn',
 'nakki',
 'tharam',
 'ninte',
 'poottil',
 'njan',
 'sugham',
 'tagram',
 'Thanglk',
 'ellam']

In [96]:
# printing first 20 tokenized words of corpus, so as to check wheteher belongs to first tweets
all_words[-20:]

['URL',
 'Jesla',
 'nayindamolleeeeeeeeeeeeeeeeeeee',
 'Kashtamana',
 'nee',
 'Covid',
 'onnu',
 'control',
 'cheyan',
 'parayallo',
 'pereyum',
 'shreddikathe',
 'fish',
 'bhangy',
 'aswathychavar',
 'undo',
 'ezuthapuram',
 'vayich',
 'news',
 'undakatheda']

In [97]:
# However, we do not want the duplicate words.
# We can retrieve all the unique words from a list by passing the list into the set function

unique_words = set(all_words)
print(len(unique_words))

15430


In [98]:
unique_words

{'niroopakaronnum',
 'ivalaanu',
 'paravedi',
 'chora',
 'vadaa',
 'agne',
 'vayanayum',
 'vishwsikunnilla',
 'Natile',
 'niyum',
 'nondhuu',
 'Ivarokke',
 'umbi',
 'Edooo',
 'tutangunne',
 'pazham',
 'chakedo',
 'bhayankaram',
 'kettichu',
 'manushyante',
 'Strong',
 'Ival',
 'wizard',
 'kollanda',
 'Prime',
 'edapedan',
 'ooroonnu',
 'cheyarutheruthu',
 'kurachoke',
 'konthan',
 'kaanichittu',
 'ayalum',
 'sabari',
 'nokiyalum',
 'jailil',
 'pusthakathil',
 'ivanmarde',
 'Mansakshi',
 'kabaril',
 'chavarkkare',
 'ingale',
 'chethe',
 'idunna',
 'learn',
 'kanunundo',
 'thannai',
 'pothu',
 'ramalan',
 'padiURL',
 'vedivechu',
 'pooora',
 'athyavishyathinu',
 'kuttikalkk',
 'jihadikal',
 'achaan',
 'samoohathinu',
 'tallanam',
 'enu',
 'thenddi',
 'Caro',
 'marchuURL',
 'orthirikkuvennulathanu',
 'partikale',
 'Keralthil',
 'Athukonde',
 'kazukaan',
 'aayittum',
 'kaanikkandatu',
 'kazhichaal',
 'akanda',
 'ivanmaru',
 'nadathanum',
 'kondala',
 'cheythittu',
 'kaannikkunnavarey',
 'k

In [99]:
#we convert all the sentences in our corpus to their numeric form and display them on the console.
#The output looks like this:
vocab_length=15450
embedded_sentences = [one_hot(sent, vocab_length) for sent in corpus]
print(embedded_sentences )

[[9306, 13282, 14805, 9653, 2216, 9771, 2364], [13829, 11686, 13020, 6421, 3485, 7819, 13644, 10375, 13767, 4927, 551], [2180, 2561, 15022, 9599, 13887, 9022], [2502, 10898, 4873, 13303, 1262, 12929, 13303, 12970, 12644], [641, 10602, 11862, 12550, 5657, 6559, 6783, 5657, 4412, 4873, 837, 13504, 14689], [5637, 3241, 6299, 11261, 937, 12683, 8517], [9653, 10915, 1504, 4499, 10021], [4754, 9483], [361, 6560, 14428, 11116, 11240, 280], [8803, 2293, 4902, 7937, 14974], [14185, 5719, 7727, 5098, 8139, 916], [1360, 5278, 2284, 12617, 14050, 9922], [12950, 6679, 4261, 12745, 9251], [15198, 13010, 13736, 97, 11537, 15444, 5471, 6379, 9279], [5905, 4940, 13939, 14236, 13584, 12040, 11422], [4432, 7052, 3328, 14822, 13554, 12171, 8464, 10195, 7690, 12874], [7404, 12128, 1728, 10182, 6758, 8377, 4175, 5505, 10182, 14326, 549, 6452, 14407, 5025, 6305, 14402, 9091, 13325], [3125, 15046, 14064, 5851, 7672, 2543, 4041, 7246, 10539, 13300, 2970, 4529, 10688, 12646, 8812, 15126, 6126, 14541, 3602], [60

In [100]:
embedded_sentences[0]

[9306, 13282, 14805, 9653, 2216, 9771, 2364]

In [101]:
# The embedding layer expects sentences to be of equal size. However, our encoded sentences are of different sizes.
# One way to make all the sentences of uniform size is to increase the lenght of all the sentences 
# and make it equal to the length of the largest sentence. 

# Let's first find the largest sentence in our corpus and then 
# we will increase the length of all the sentences to the length of the largest sentence.

word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [102]:
length_long_sentence

65

In [103]:
# Next to make all the sentences of equal size, 
# we will add zeros to the empty indexes that will be created as a result of increasing the sentence length.
# To append the zeros at the end of the sentencses, we can use the pad_sequences method. 
# The first parameter is the list of encoded sentences of unequal sizes, 
# the second parameter is the size of the longest sentence or the padding index,
# while the last parameter is padding where you specify post to add padding at the end of sentences.

In [104]:
# we can see zeros at the end of the padded sentences.

padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences), len(padded_sentences), padded_sentences.shape

[[ 9306 13282 14805 ...     0     0     0]
 [13829 11686 13020 ...     0     0     0]
 [ 2180  2561 15022 ...     0     0     0]
 ...
 [ 7753 11658  9224 ...     0     0     0]
 [ 6884  3691  3947 ...     0     0     0]
 [11019  5263  9575 ...     0     0     0]]


(None, 2800, (2800, 65))

In [105]:
padded_sentences[0]

array([ 9306, 13282, 14805,  9653,  2216,  9771,  2364,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0])

In [106]:
X_test.shape

(1200,)

In [107]:
X_test

2936    Oru trend follow cheyyunna pole e filmne kutta...
2606       Veruthe kittiyalum aarkum venda e nayinte mole
2441                     Pvm sunny chechi allah uvvee eth
3415                  avale angot petrl oyich kathichoode
2658    year ayittum ennu varay ottakku oridathum vida...
                              ...                        
1607    Innalai kilirtha kurai kochammamaryum vichondu...
2759               Moori Biriyani Eppozhum Kazhikkunnavar
1540       ivaloke keralathil thane jaddi illathe nadakum
418             Onnu poyediii bayagara different ayi poyi
1810                     Evaley okkey pulikkabinadikkanam
Name: Msg_without_Stopwords, Length: 1200, dtype: object

In [108]:
test_corpus=X_test
type(test_corpus)
test_corpus

2936    Oru trend follow cheyyunna pole e filmne kutta...
2606       Veruthe kittiyalum aarkum venda e nayinte mole
2441                     Pvm sunny chechi allah uvvee eth
3415                  avale angot petrl oyich kathichoode
2658    year ayittum ennu varay ottakku oridathum vida...
                              ...                        
1607    Innalai kilirtha kurai kochammamaryum vichondu...
2759               Moori Biriyani Eppozhum Kazhikkunnavar
1540       ivaloke keralathil thane jaddi illathe nadakum
418             Onnu poyediii bayagara different ayi poyi
1810                     Evaley okkey pulikkabinadikkanam
Name: Msg_without_Stopwords, Length: 1200, dtype: object

In [109]:
all_words_test = []
for t_sent in test_corpus:
    test_tokenize_word = word_tokenize(t_sent)
    for word in test_tokenize_word:
            all_words_test.append(word)


In [110]:
len(all_words_test)

11661

In [111]:
test_unique_words = set(all_words_test)
print(len(test_unique_words))

7465


In [112]:
test_vocab_length=11500
test_embedded_sentences = [one_hot(t_sent, test_vocab_length) for t_sent in test_corpus]
print(test_embedded_sentences)

[[3740, 4760, 7217, 8872, 8344, 2294, 2539, 7908, 7163, 5767, 8229, 10702, 7553, 5947], [9867, 10077, 1810, 1779, 2294, 4825, 1350], [7987, 7219, 7581, 6294, 3338, 9505], [10160, 8842, 4458, 2844, 9442], [1270, 6001, 3897, 1182, 9397, 9121, 6167, 9927, 11281, 2971, 8180, 3740, 1256, 9208, 8558, 3823, 6156, 716, 5360], [7588, 529, 4567, 11157, 1760, 3291, 2671, 10881, 10865, 9111, 7620], [5984, 9661, 6220, 4262, 8180, 4437, 6721, 10709], [8180, 6248, 6549, 10089], [856, 9340, 4061, 6000, 8881], [7623, 7916, 6385, 8890, 10065, 7795, 3573, 222, 3132, 6281, 8010, 7346, 6351, 4200, 5700], [6549, 689, 6544, 2632, 10680, 5063, 3718], [4391, 843, 2784, 3098, 8432, 2129, 9207, 1123, 2944, 9129], [385, 7277, 5311, 1478, 6379], [7048, 2845, 9740, 25, 7901, 8186, 5235, 7387, 5374, 5731, 8942, 10227, 10775, 3954, 3897, 9224, 10118, 7274, 7672], [3342, 6475, 5695, 10349, 10128, 2444, 2312], [11258, 159, 3236, 9251, 5121, 6320, 10739, 1109, 3519], [9575, 1773, 6369, 5111, 3535, 2808, 5111, 3630, 2845

In [113]:
test_embedded_sentences[0]

[3740,
 4760,
 7217,
 8872,
 8344,
 2294,
 2539,
 7908,
 7163,
 5767,
 8229,
 10702,
 7553,
 5947]

In [114]:
test_word_count = lambda sentence: len(word_tokenize(sentence))
test_longest_sentence = max(test_corpus, key=test_word_count)
length_test_long_sentence = len(word_tokenize(test_longest_sentence))
length_test_long_sentence

60

In [115]:
test_padded_sentences = pad_sequences(test_embedded_sentences, length_long_sentence, padding='post')
print(test_padded_sentences), len(test_padded_sentences), test_padded_sentences.shape

[[ 3740  4760  7217 ...     0     0     0]
 [ 9867 10077  1810 ...     0     0     0]
 [ 7987  7219  7581 ...     0     0     0]
 ...
 [ 1675  4287  9390 ...     0     0     0]
 [ 9376  4318 10644 ...     0     0     0]
 [ 9125  4372  6762 ...     0     0     0]]


(None, 1200, (1200, 65))

In [116]:
test_padded_sentences[0]

array([ 3740,  4760,  7217,  8872,  8344,  2294,  2539,  7908,  7163,
        5767,  8229, 10702,  7553,  5947,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0])

In [173]:
model = keras.Sequential([
    keras.layers.Embedding(vocab_length, 200, input_length=length_long_sentence),
   # keras.layers.GlobalAveragePooling1D(),
    keras.layers.Flatten(),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 65, 200)           3090000   
_________________________________________________________________
flatten_3 (Flatten)          (None, 13000)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 13001     
Total params: 3,103,001
Trainable params: 3,103,001
Non-trainable params: 0
_________________________________________________________________


In [175]:
model.fit(padded_sentences, y_train, epochs=4, verbose=1)

Train on 2800 samples
Epoch 1/4
2800/2800 [==============================] - 5s 2ms/sample - loss: 0.6931 - accuracy: 0.5079
Epoch 2/4
2800/2800 [==============================] - 5s 2ms/sample - loss: 0.5454 - accuracy: 0.8904
Epoch 3/4
2800/2800 [==============================] - 5s 2ms/sample - loss: 0.2176 - accuracy: 0.9861
Epoch 4/4
2800/2800 [==============================] - 5s 2ms/sample - loss: 0.0630 - accuracy: 0.9982


In [176]:
# X, Y
padded_sentences.shape, y_train.shape

((2800, 65), (2800,))

In [177]:
ytest=y_test.to_numpy()
test_padded_sentences.shape, ytest.shape

((1200, 65), (1200,))

In [178]:
loss, accuracy = model.evaluate(test_padded_sentences, ytest, verbose=1)
print('Accuracy: %f' % (accuracy*100))

1200/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

Accuracy: 52.083331


In [179]:
loss, accuracy = model.evaluate(padded_sentences, y_train, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 99.964285


In [180]:
ytest=y_test.to_numpy()
test_padded_sentences.shape, ytest.shape

((1200, 65), (1200,))

In [181]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score

In [182]:
yhat_probs=model.predict(test_padded_sentences, verbose=0)
yhat_probs

array([[0.7486387 ],
       [0.39202517],
       [0.44806054],
       ...,
       [0.29235807],
       [0.36973834],
       [0.49591827]], dtype=float32)

In [183]:
yhat_classes=model.predict_classes(test_padded_sentences, verbose=0)
yhat_classes

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [184]:
cm=tf.math.confusion_matrix(ytest, yhat_classes)
cm

<tf.Tensor: id=9606, shape=(2, 2), dtype=int32, numpy=
array([[371, 253],
       [322, 254]])>

In [185]:
accuracy = accuracy_score(ytest, yhat_classes)
print('Accuracy: %f' % accuracy)

precision = precision_score(ytest, yhat_classes)
print('Precision: %f' % precision)

recall = recall_score(ytest, yhat_classes)
print('Recall: %f' % recall)

f1 = f1_score(ytest, yhat_classes)
print('F1 score: %f' % f1)

Accuracy: 0.520833
Precision: 0.500986
Recall: 0.440972
F1 score: 0.469067
