# importing necesary modeules

In [3]:
from sklearn.datasets import load_files
import pandas as pd

# Original Tamil Dataset has Labels columns serially; so datasets is Sorted as per ID column

In [4]:
Tam_data=pd.read_excel("COPY_Tamil-Codemixed_offensive_data_Training-Tweet-HL.xlsx", header=None, )
Tam_data

0                                                  1    2
0      TA_TW999  @USER Ila, Padam semaya irukkum bro. Enaku rom...  NOT
1      TA_HL100  Iyaooo Kovam pattutene sothula visatha vachuru...  NOT
2     TA_HL1000               yematha arambichitanunga nambathinga  NOT
3     TA_HL1001  Yen allah thavira yarodaiya sollu unmai illa n...  NOT
4     TA_HL1002  yen pa vera heroine kedaikkalaya ippadi tha ke...  NOT
...         ...                                                ...  ...
3995   TA_TW991  @USER Temper paathathu illa.. over sentiment n...  NOT
3996   TA_TW994  Pavam da andha pinju kozhantha epdi ipdi manas...  NOT
3997   TA_TW995  RT @USER : unaku avaru pesanum nu irundha avar...  OFF
3998   TA_TW997  RT @USER : Waking up with rachitha watha Enna ...  OFF
3999   TA_TW998  Siluku ku tuf kudukura kalaignar tv news reade...  OFF

[4000 rows x 3 columns]

In [5]:
Tam_data=Tam_data.rename(columns={0:'ID', 1:'Tweets', 2:'Labels'})

In [6]:
Tam_data[0:10]

ID                                             Tweets Labels
0   TA_TW999  @USER Ila, Padam semaya irukkum bro. Enaku rom...    NOT
1   TA_HL100  Iyaooo Kovam pattutene sothula visatha vachuru...    NOT
2  TA_HL1000               yematha arambichitanunga nambathinga    NOT
3  TA_HL1001  Yen allah thavira yarodaiya sollu unmai illa n...    NOT
4  TA_HL1002  yen pa vera heroine kedaikkalaya ippadi tha ke...    NOT
5  TA_HL1003  yenda arivu kettavanae unakulam corana vara ku...    OFF
6  TA_HL1004  yenda itha, yen pona year podala? yepo kasta p...    NOT
7  TA_HL1005  yenda saniyan pudichavanugala yenda ippadilam ...    OFF
8  TA_HL1006  yenn da yen ivangaluku antha coronove parava i...    NOT
9  TA_HL1007                    yenna kandravi kadhalo! cheee..    OFF

In [7]:
# pip install regex

# importing necesary modeules

In [8]:
import regex
import re
import numpy as np

In [9]:
labels,counts=np.unique(Tam_data['Labels'],return_counts=True)

In [10]:
print(labels,counts)

['NOT' 'OFF' 'OFf' 'not'] [2019 1979    1    1]


In [11]:
Tam_data['Labels']

0       NOT
1       NOT
2       NOT
3       NOT
4       NOT
       ... 
3995    NOT
3996    NOT
3997    OFF
3998    OFF
3999    OFF
Name: Labels, Length: 4000, dtype: object

In [12]:
lab=Tam_data['Labels']

In [13]:
low_lab=lab.str.lower()

In [14]:
Tam_lab=pd.DataFrame(low_lab)
Tam_lab.columns=['Lowlabels']

In [15]:
Tam_data=pd.concat([Tam_data,Tam_lab], axis=1)

In [16]:
Tam_data['Lowlabels']=Tam_data['Lowlabels'].apply(lambda x: 1 if x=="off" else 0)

In [17]:
Tam_data

ID                                             Tweets Labels  \
0      TA_TW999  @USER Ila, Padam semaya irukkum bro. Enaku rom...    NOT   
1      TA_HL100  Iyaooo Kovam pattutene sothula visatha vachuru...    NOT   
2     TA_HL1000               yematha arambichitanunga nambathinga    NOT   
3     TA_HL1001  Yen allah thavira yarodaiya sollu unmai illa n...    NOT   
4     TA_HL1002  yen pa vera heroine kedaikkalaya ippadi tha ke...    NOT   
...         ...                                                ...    ...   
3995   TA_TW991  @USER Temper paathathu illa.. over sentiment n...    NOT   
3996   TA_TW994  Pavam da andha pinju kozhantha epdi ipdi manas...    NOT   
3997   TA_TW995  RT @USER : unaku avaru pesanum nu irundha avar...    OFF   
3998   TA_TW997  RT @USER : Waking up with rachitha watha Enna ...    OFF   
3999   TA_TW998  Siluku ku tuf kudukura kalaignar tv news reade...    OFF   

      Lowlabels  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
3995          0  
3996          0  
3997          1  
3998          1  
3999          1  

[4000 rows x 4 columns]

# storing tweets into msg. msg type is pandas series

In [18]:
msg=Tam_data['Tweets']

# Removing @USER at the start of each tweet

In [19]:
msg_USER_TAG=msg.str.replace(r"@USER |RT| #TAG", ' ')
msg_USER_TAG[3830:3840]

3830     Gud morning samathu Ennavam, enna aachu 1 mon...
3831     Sema acting ms Bhaskar ku ..munishkath kuda s...
3832     semaya irukum Pattison ku upgraded suit ah cl...
3833     Sila director thanoodaiya nilai padil sattrum...
3834     sir ithellam romba too much...amma irukumpoth...
3835       : ***mmala Silent ah Navundhuru Wanted vara...
3836     sir naanga 300 tamil people including pregnan...
3837     Sk anna tha romba feeling a irukum pothu movi...
3838     Dai bro unaku veetla drishti suththi poda sol...
3839     Solo than bro ponen Rendume try pannen mudila...
Name: Tweets, dtype: object

# Encoding  😁😁 & many other symbols to ASCII; so that those r removed from tweets. 
# After removal we can see msg is encoded and started with b'

In [20]:
msg_USER_Encod=msg_USER_TAG.str.encode("ascii", "ignore")
msg_USER_Encod[2508:2520], type(msg_USER_Encod)

(2508    b' Unmayaina sambavam dha mental koothi. Poi g...
 2509    b' unna apudiyae thugittu poi NH road la divid...
 2510    b' unna maari thevdiya paiyanukku ithayachi re...
 2511    b' Unna mathiri 10 peruku porantha thevidiya p...
 2512    b' Unna mathiri kiruku pundaikittala appaditha...
 2513    b' Unnala madurai ku thaanda asingam onnu adik...
 2514    b' Unnoda pazakatha ethuku enkita soldra namba...
 2515    b' unnoda porappu oru echa thulukachi thevudiy...
 2516    b' Unta na annaike solliten junni ya pathi sol...
 2517    b' unvela pundaya ne paru da othaa vekka punda...
 2518    b' Vaaa daa vaaaa Kulla thevidiya movane Ungom...
 2519    b' Vada punda mavane nalla urinju urinju Vai v...
 Name: Tweets, dtype: object, pandas.core.series.Series)

In [21]:
print(msg_USER_Encod[2508])

b' Unmayaina sambavam dha mental koothi. Poi google panni paaru neyveli issue va'


# Decoding msg to format where we can see b' is removed 

In [22]:
msg_USER_decod=msg_USER_Encod.str.decode(encoding = 'ASCII')

In [23]:
print(msg_USER_decod[2508:2520])

2508     Unmayaina sambavam dha mental koothi. Poi goo...
2509     unna apudiyae thugittu poi NH road la divider...
2510     unna maari thevdiya paiyanukku ithayachi repl...
2511     Unna mathiri 10 peruku porantha thevidiya pay...
2512     Unna mathiri kiruku pundaikittala appadithand...
2513     Unnala madurai ku thaanda asingam onnu adikka...
2514     Unnoda pazakatha ethuku enkita soldra namba n...
2515     unnoda porappu oru echa thulukachi thevudiya ...
2516     Unta na annaike solliten junni ya pathi solla...
2517     unvela pundaya ne paru da othaa vekka punda i...
2518     Vaaa daa vaaaa Kulla thevidiya movane Ungomma...
2519     Vada punda mavane nalla urinju urinju Vai vec...
Name: Tweets, dtype: object


# Removing digits 

In [24]:
msg_Digit = msg_USER_decod.str.replace(r'[0-9]', ' ')

In [25]:
msg_Digit[3830:3840]

3830     Gud morning samathu Ennavam, enna aachu   mon...
3831     Sema acting ms Bhaskar ku ..munishkath kuda s...
3832     semaya irukum Pattison ku upgraded suit ah cl...
3833     Sila director thanoodaiya nilai padil sattrum...
3834     sir ithellam romba too much...amma irukumpoth...
3835       : ***mmala Silent ah Navundhuru Wanted vara...
3836     sir naanga     tamil people including pregnan...
3837     Sk anna tha romba feeling a irukum pothu movi...
3838     Dai bro unaku veetla drishti suththi poda sol...
3839     Solo than bro ponen Rendume try pannen mudila...
Name: Tweets, dtype: object

# Removing Special Characters

In [26]:
msg_SpChar = msg_Digit.str.replace(r'[^\w\d\s]', ' ')

In [27]:
msg_SpChar[3830:3840]

3830     Gud morning samathu Ennavam  enna aachu   mon...
3831     Sema acting ms Bhaskar ku   munishkath kuda s...
3832     semaya irukum Pattison ku upgraded suit ah cl...
3833     Sila director thanoodaiya nilai padil sattrum...
3834     sir ithellam romba too much   amma irukumpoth...
3835            mmala Silent ah Navundhuru Wanted vara...
3836     sir naanga     tamil people including pregnan...
3837     Sk anna tha romba feeling a irukum pothu movi...
3838     Dai bro unaku veetla drishti suththi poda sol...
3839     Solo than bro ponen Rendume try pannen mudila...
Name: Tweets, dtype: object

# Removing  xtra Whitespaces 

In [28]:
msg_Spac = msg_SpChar.str.replace(r'\s+', ' ')

In [29]:
msg_Hyp = msg_Spac.str.replace(r'_','')

In [30]:
msg_Hyp[3830:3840]

3830     Gud morning samathu Ennavam enna aachu month ...
3831     Sema acting ms Bhaskar ku munishkath kuda sil...
3832     semaya irukum Pattison ku upgraded suit ah cl...
3833     Sila director thanoodaiya nilai padil sattrum...
3834     sir ithellam romba too much amma irukumpothu ...
3835     mmala Silent ah Navundhuru Wanted varadha Uno...
3836     sir naanga tamil people including pregnant la...
3837     Sk anna tha romba feeling a irukum pothu movi...
3838     Dai bro unaku veetla drishti suththi poda sol...
3839     Solo than bro ponen Rendume try pannen mudila...
Name: Tweets, dtype: object

# storing msg_spec (i.e. processed data) into dataframe Msg_df

In [31]:
Msg_df=pd.DataFrame(msg_Hyp)
Msg_df.columns=['Msg_with_Stopwords']

# Removing Null values 

In [32]:
Msg_df['Msg_with_Stopwords']=Msg_df['Msg_with_Stopwords'].fillna("")

In [33]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Removing Stop words 

In [34]:
stop_words = set(stopwords.words('english'))

In [35]:
Msg_df['Msg_without_Stopwords']=Msg_df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

# Counting length of each tweet for with stopwords and without stopwords & placing into dataframe : Msg_df

In [36]:
Msg_df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_with_Stopwords'].tolist()]
Msg_df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_without_Stopwords'].tolist()]

In [37]:
Msg_df[228:231]

Msg_with_Stopwords  \
228  Arivodu pesu summa ethayavathu pesagudadu vasi...   
229  arunvijay wife enna money mari erukeee vanitha...   
230  athaana Love lam Athuva varanum Varlana Vitrnu...   

                                 Msg_without_Stopwords  \
228  Arivodu pesu summa ethayavathu pesagudadu vasi...   
229  arunvijay wife enna money mari erukeee vanitha...   
230  athaana Love lam Athuva varanum Varlana Vitrnu...   

     Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  
228                      19                         19  
229                       9                          9  
230                      28                         28

# Counting Vowels and Consonents from each tweet

In [38]:
Msg_df['Vowels'] = Msg_df['Msg_without_Stopwords'].str.lower().str.count(r'[aeiou]')
Msg_df['Consonant'] = Msg_df['Msg_without_Stopwords'].str.lower().str.count(r'[a-z]') - Msg_df['Vowels']

In [39]:
Msg_df

Msg_with_Stopwords  \
0      Ila Padam semaya irukkum bro Enaku romba pudi...   
1     Iyaooo Kovam pattutene sothula visatha vachuru...   
2                  yematha arambichitanunga nambathinga   
3     Yen allah thavira yarodaiya sollu unmai illa n...   
4     yen pa vera heroine kedaikkalaya ippadi tha ke...   
...                                                 ...   
3995   Temper paathathu illa over sentiment nu endin...   
3996  Pavam da andha pinju kozhantha epdi ipdi manas...   
3997   unaku avaru pesanum nu irundha avar vitu muna...   
3998   Waking up with rachitha watha Enna ponnu da i...   
3999  Siluku ku tuf kudukura kalaignar tv news reade...   

                                  Msg_without_Stopwords  \
0     Ila Padam semaya irukkum bro Enaku romba pudic...   
1     Iyaooo Kovam pattutene sothula visatha vachuru...   
2                  yematha arambichitanunga nambathinga   
3     Yen allah thavira yarodaiya sollu unmai illa n...   
4     yen pa vera heroine kedaikkalaya ippadi tha ke...   
...                                                 ...   
3995  Temper paathathu illa sentiment nu ending la r...   
3996  Pavam da andha pinju kozhantha epdi ipdi manas...   
3997  unaku avaru pesanum nu irundha avar vitu munad...   
3998  Waking rachitha watha Enna ponnu da iva la aaa...   
3999  Siluku ku tuf kudukura kalaignar tv news reade...   

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  Vowels  Consonant  
0                         21                         14      33         46  
1                          7                          7      28         25  
2                          3                          3      14         20  
3                         16                         15      36         45  
4                         40                         40     108        142  
...                      ...                        ...     ...        ...  
3995                      16                         15      40         56  
3996                      17                         17      46         57  
3997                      16                         15      32         35  
3998                      40                         38      96        110  
3999                      36                         36     102        122  

[4000 rows x 6 columns]

In [40]:
type(Tam_data),type(Msg_df)

(pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)

# Concatinating original dataframe i.e. Mal_data and modified dataframes i.e. Msg_df into final_Data

In [41]:
final_Data=pd.concat([Msg_df, Tam_data], axis=1)

In [42]:
final_Data

Msg_with_Stopwords  \
0      Ila Padam semaya irukkum bro Enaku romba pudi...   
1     Iyaooo Kovam pattutene sothula visatha vachuru...   
2                  yematha arambichitanunga nambathinga   
3     Yen allah thavira yarodaiya sollu unmai illa n...   
4     yen pa vera heroine kedaikkalaya ippadi tha ke...   
...                                                 ...   
3995   Temper paathathu illa over sentiment nu endin...   
3996  Pavam da andha pinju kozhantha epdi ipdi manas...   
3997   unaku avaru pesanum nu irundha avar vitu muna...   
3998   Waking up with rachitha watha Enna ponnu da i...   
3999  Siluku ku tuf kudukura kalaignar tv news reade...   

                                  Msg_without_Stopwords  \
0     Ila Padam semaya irukkum bro Enaku romba pudic...   
1     Iyaooo Kovam pattutene sothula visatha vachuru...   
2                  yematha arambichitanunga nambathinga   
3     Yen allah thavira yarodaiya sollu unmai illa n...   
4     yen pa vera heroine kedaikkalaya ippadi tha ke...   
...                                                 ...   
3995  Temper paathathu illa sentiment nu ending la r...   
3996  Pavam da andha pinju kozhantha epdi ipdi manas...   
3997  unaku avaru pesanum nu irundha avar vitu munad...   
3998  Waking rachitha watha Enna ponnu da iva la aaa...   
3999  Siluku ku tuf kudukura kalaignar tv news reade...   

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  Vowels  Consonant  \
0                         21                         14      33         46   
1                          7                          7      28         25   
2                          3                          3      14         20   
3                         16                         15      36         45   
4                         40                         40     108        142   
...                      ...                        ...     ...        ...   
3995                      16                         15      40         56   
3996                      17                         17      46         57   
3997                      16                         15      32         35   
3998                      40                         38      96        110   
3999                      36                         36     102        122   

             ID                                             Tweets Labels  \
0      TA_TW999  @USER Ila, Padam semaya irukkum bro. Enaku rom...    NOT   
1      TA_HL100  Iyaooo Kovam pattutene sothula visatha vachuru...    NOT   
2     TA_HL1000               yematha arambichitanunga nambathinga    NOT   
3     TA_HL1001  Yen allah thavira yarodaiya sollu unmai illa n...    NOT   
4     TA_HL1002  yen pa vera heroine kedaikkalaya ippadi tha ke...    NOT   
...         ...                                                ...    ...   
3995   TA_TW991  @USER Temper paathathu illa.. over sentiment n...    NOT   
3996   TA_TW994  Pavam da andha pinju kozhantha epdi ipdi manas...    NOT   
3997   TA_TW995  RT @USER : unaku avaru pesanum nu irundha avar...    OFF   
3998   TA_TW997  RT @USER : Waking up with rachitha watha Enna ...    OFF   
3999   TA_TW998  Siluku ku tuf kudukura kalaignar tv news reade...    OFF   

      Lowlabels  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
3995          0  
3996          0  
3997          1  
3998          1  
3999          1  

[4000 rows x 10 columns]

# Dropping the columns Tweets and ID

In [43]:
final_Data=final_Data.drop(['Tweets', 'ID', 'Labels'], axis=1)

# Showing the Dataframe : final_Data

In [44]:
final_Data

Msg_with_Stopwords  \
0      Ila Padam semaya irukkum bro Enaku romba pudi...   
1     Iyaooo Kovam pattutene sothula visatha vachuru...   
2                  yematha arambichitanunga nambathinga   
3     Yen allah thavira yarodaiya sollu unmai illa n...   
4     yen pa vera heroine kedaikkalaya ippadi tha ke...   
...                                                 ...   
3995   Temper paathathu illa over sentiment nu endin...   
3996  Pavam da andha pinju kozhantha epdi ipdi manas...   
3997   unaku avaru pesanum nu irundha avar vitu muna...   
3998   Waking up with rachitha watha Enna ponnu da i...   
3999  Siluku ku tuf kudukura kalaignar tv news reade...   

                                  Msg_without_Stopwords  \
0     Ila Padam semaya irukkum bro Enaku romba pudic...   
1     Iyaooo Kovam pattutene sothula visatha vachuru...   
2                  yematha arambichitanunga nambathinga   
3     Yen allah thavira yarodaiya sollu unmai illa n...   
4     yen pa vera heroine kedaikkalaya ippadi tha ke...   
...                                                 ...   
3995  Temper paathathu illa sentiment nu ending la r...   
3996  Pavam da andha pinju kozhantha epdi ipdi manas...   
3997  unaku avaru pesanum nu irundha avar vitu munad...   
3998  Waking rachitha watha Enna ponnu da iva la aaa...   
3999  Siluku ku tuf kudukura kalaignar tv news reade...   

      Msg_with_Stopwords_Len  Msg_without_Stopwords_Len  Vowels  Consonant  \
0                         21                         14      33         46   
1                          7                          7      28         25   
2                          3                          3      14         20   
3                         16                         15      36         45   
4                         40                         40     108        142   
...                      ...                        ...     ...        ...   
3995                      16                         15      40         56   
3996                      17                         17      46         57   
3997                      16                         15      32         35   
3998                      40                         38      96        110   
3999                      36                         36     102        122   

      Lowlabels  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
3995          0  
3996          0  
3997          1  
3998          1  
3999          1  

[4000 rows x 7 columns]

# splitting the dataset into train=70% & test=30% where X=final_Data.Msg_without_Stopwords & Y=final_Data.Labels

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(final_Data.Msg_without_Stopwords, final_Data.Lowlabels,  random_state=40, test_size=0.3)

In [46]:
len(X_train), len(y_train), len(X_test), len(y_test)

(2800, 2800, 1200, 1200)

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(analyzer='word', lowercase=True, ngram_range=(1,4))
X=tfidf.fit_transform(X_train)
Y=y_train
tfidf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 4), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [48]:
char_tfidf=TfidfVectorizer(analyzer='char', lowercase=True, ngram_range=(1, 7))
X_char=char_tfidf.fit_transform(X_train) 
char_tfidf

TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 7), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

#  tfidf word  n-gram(1,4) extracted : features  = 117173
#  tfidf char  n-gram(1,7) extracted : features  = 325902


In [49]:
tfidf.get_feature_names()

['aa',
 'aa athellame',
 'aa athellame solli',
 'aa athellame solli thitra',
 'aa da',
 'aa da ne',
 'aa da un',
 'aa da un english',
 'aa gaya',
 'aa gaya evlo',
 'aa gaya evlo per',
 'aa irukaanga',
 'aa irukan',
 'aa irukan ithukumela',
 'aa irukan ithukumela avana',
 'aa irukanga',
 'aa irukanga ipdilam',
 'aa irukanga ipdilam panna',
 'aa irukku',
 'aa iruku',
 'aa iruku athanala',
 'aa iruku athanala na',
 'aa irukum',
 'aa irukum ippo',
 'aa irukum ippo karaname',
 'aa kaatuthu',
 'aa kaatuthu konjam',
 'aa kaatuthu konjam decent',
 'aa ku',
 'aa ku romba',
 'aa ku romba kastam',
 'aa kuppa',
 'aa kuppa thottiyil',
 'aa kuppa thottiyil veesittu',
 'aa lossu',
 'aa lossu di',
 'aa lossu di nee',
 'aa offical',
 'aa offical ah',
 'aa offical ah release',
 'aa paathu',
 'aa paathu thaa',
 'aa paathu thaa bro',
 'aa pandra',
 'aa pandra porama',
 'aa pandra porama pidichava',
 'aa pannitu',
 'aa pannitu irukka',
 'aa pannitu irukka naan',
 'aa periyarism',
 'aa periyarism panadha',


In [50]:
char_tfidf.get_feature_names()

[' ',
 ' a',
 ' a ',
 ' a d',
 ' a d ',
 ' a d t',
 ' a d th',
 ' a n',
 ' a ne',
 ' a neg',
 ' a nega',
 ' a p',
 ' a p ',
 ' a p j',
 ' a p j ',
 ' aa',
 ' aa ',
 ' aa a',
 ' aa at',
 ' aa ath',
 ' aa d',
 ' aa da',
 ' aa da ',
 ' aa g',
 ' aa ga',
 ' aa gay',
 ' aa i',
 ' aa ir',
 ' aa iru',
 ' aa k',
 ' aa ka',
 ' aa kaa',
 ' aa ku',
 ' aa ku ',
 ' aa kup',
 ' aa o',
 ' aa of',
 ' aa off',
 ' aa p',
 ' aa pa',
 ' aa paa',
 ' aa pan',
 ' aa pe',
 ' aa per',
 ' aa pes',
 ' aa s',
 ' aa su',
 ' aa sup',
 ' aa t',
 ' aa ta',
 ' aa tan',
 ' aa th',
 ' aa tha',
 ' aa v',
 ' aa va',
 ' aa van',
 ' aaa',
 ' aaa ',
 ' aaa c',
 ' aaa co',
 ' aaa k',
 ' aaa ke',
 ' aaa p',
 ' aaa po',
 ' aaah',
 ' aaah ',
 ' aaah d',
 ' aaahh',
 ' aaahh ',
 ' aaal',
 ' aaale',
 ' aaale ',
 ' aaat',
 ' aaath',
 ' aaatha',
 ' aac',
 ' aach',
 ' aacha',
 ' aachae',
 ' aachar',
 ' aache',
 ' aache ',
 ' aachi',
 ' aachi ',
 ' aachu',
 ' aachu ',
 ' aachun',
 ' aad',
 ' aadi',
 ' aadic',
 ' aadich',
 ' aadik',
 ' 

In [51]:
# length of Vocabulary / features extracted 
len(tfidf.vocabulary_), len(char_tfidf.vocabulary_), len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())

(117173, 325902, 117173, 325902)

In [138]:
# X : Word features from X_train
# X_char : Char Features from X_train
X, X_char

(<2800x117173 sparse matrix of type '<class 'numpy.float64'>'
 	with 166592 stored elements in Compressed Sparse Row format>,
 <2800x325902 sparse matrix of type '<class 'numpy.float64'>'
 	with 1616412 stored elements in Compressed Sparse Row format>)

In [139]:
# Combining X ( Word features) & X_char (Char Features) using hstack
from scipy.sparse import hstack
train=hstack([X,X_char])
train

<2800x443075 sparse matrix of type '<class 'numpy.float64'>'
	with 1783004 stored elements in COOrdinate format>

In [140]:
# transforming X_test into  Word features into Xt
# transforming X_test into  char features into Xt_char

Xt=tfidf.transform(X_test) 
Xt_char=char_tfidf.transform(X_test) 

In [141]:
Xt, Xt_char

(<1200x117173 sparse matrix of type '<class 'numpy.float64'>'
 	with 29608 stored elements in Compressed Sparse Row format>,
 <1200x325902 sparse matrix of type '<class 'numpy.float64'>'
 	with 594596 stored elements in Compressed Sparse Row format>)

In [142]:
# Combining Xt ( Word features) & Xt_char (Char Features) using hstack
traintest=hstack([Xt,Xt_char])
traintest

<1200x443075 sparse matrix of type '<class 'numpy.float64'>'
	with 624204 stored elements in COOrdinate format>

# test_data Provided by organizers 
# Applying & Transforming : TF/IDF Word ngram(1,4) & Char ngram(1,7) and Combine word & Char ngram features

In [143]:
tam_hasoc=pd.read_excel("Tamil_hasoc_tanglish_test_without_labels.xlsx", header=None)
tam_hasoc=tam_hasoc.rename(columns={0:'id', 1:'text'})
test_Tam_hasoc=tam_hasoc['text']

test_Tam_Hasoc_word=tfidf.transform(test_Tam_hasoc)
test_Tam_Hasoc_char=char_tfidf.transform(test_Tam_hasoc)
test_Tam_Hasoc_word_char=hstack([test_Tam_Hasoc_word, test_Tam_Hasoc_char])

In [144]:
test_Tam_Hasoc_word, test_Tam_Hasoc_char, test_Tam_Hasoc_word_char

(<940x117173 sparse matrix of type '<class 'numpy.float64'>'
 	with 12772 stored elements in Compressed Sparse Row format>,
 <940x325902 sparse matrix of type '<class 'numpy.float64'>'
 	with 424160 stored elements in Compressed Sparse Row format>,
 <940x443075 sparse matrix of type '<class 'numpy.float64'>'
 	with 436932 stored elements in COOrdinate format>)

In [145]:
#Importing Necessary modules

In [146]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [147]:
def trainer(model_obj, param, X, X_char, train, traintest, Y, y_test):
    # Training Classifier  with TF-IDF Features Word n-gram(1,4)
    GSCV=GridSearchCV(model_obj, param , cv=5,return_train_score=False)
    GSCV.fit(X,Y)
    print("Accuracy of Word n-gram(1,4) :", (GSCV.score(tfidf.transform(X_test), y_test)))
    #Printing Classification Report
    predict=GSCV.predict(Xt)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=GSCV.predict(test_Tam_Hasoc_word)

  #Training Classifier with TF-IDF Features Char n-gram(1,7)
    GSCV.fit(X_char, Y)
    print("Accuracy of Char n-gram(1,7) :", (GSCV.score(char_tfidf.transform(X_test), y_test)))
    predict=GSCV.predict(Xt_char)
    print(classification_report(y_test, predict))
   #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=GSCV.predict(test_Tam_Hasoc_char)

                      
    #Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    GSCV.fit(train, Y)
    print("Accuracy of Combinining word & Char n-gram", (GSCV.score(traintest, y_test)))
    #Printing Classification Report
    predict=GSCV.predict(traintest)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=GSCV.predict(test_Tam_Hasoc_word_char)
    
    return word, char, word_char

# Implementing SVC 

In [72]:
from sklearn.svm import SVC
svc=SVC()
print("SVC")
param={'kernel':('linear', 'rbf'), 'gamma':('auto', 'scale'), 'C':[0.9, 10, 20, 30]}
w_svc,c_svc,wc_svc=trainer(svc,param, X, X_char, train, traintest, Y, y_test)

SVC
Accuracy of Word n-gram(1,4) : 0.8358333333333333
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       617
           1       0.83      0.84      0.83       583

    accuracy                           0.84      1200
   macro avg       0.84      0.84      0.84      1200
weighted avg       0.84      0.84      0.84      1200

Best Parameters  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Best Score  0.8407142857142857
 
Confusion Matrix
[[514 103]
 [ 94 489]]
 
Accuracy of Char n-gram(1,7) : 0.865
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       617
           1       0.86      0.86      0.86       583

    accuracy                           0.86      1200
   macro avg       0.86      0.86      0.86      1200
weighted avg       0.86      0.86      0.86      1200

Best Parameters  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}
Best Score  0.8592857142857143
 
Confusion Matrix
[[539 

In [74]:
w_svc=pd.DataFrame(w_svc, columns=["Word_SVC"])
c_svc=pd.DataFrame(c_svc, columns=["Char_SVC"])
wc_svc=pd.DataFrame(wc_svc, columns=["Combine Word Char_SVC"])
res_svm=pd.concat([w_svc,c_svc,wc_svc], axis=1)
res_svm

Word_SVC  Char_SVC  Combine Word Char_SVC
0           1         1                      1
1           1         0                      0
2           1         1                      1
3           1         1                      1
4           1         1                      1
..        ...       ...                    ...
935         1         1                      1
936         0         1                      0
937         0         0                      0
938         0         0                      0
939         1         1                      1

[940 rows x 3 columns]

# Implementing Multinomial Naive Bayes 

In [148]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB(alpha=2.0)
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train, traintest, Y, y_test)

Multi Nominal Bayes
Accuracy of Word n-gram(1,4) : 0.8366666666666667
              precision    recall  f1-score   support

           0       0.84      0.84      0.84       617
           1       0.83      0.84      0.83       583

    accuracy                           0.84      1200
   macro avg       0.84      0.84      0.84      1200
weighted avg       0.84      0.84      0.84      1200

Best Parameters  {'alpha': 1.2}
Best Score  0.8464285714285714
 
Confusion Matrix
[[516 101]
 [ 95 488]]
 
Accuracy of Char n-gram(1,7) : 0.8433333333333334
              precision    recall  f1-score   support

           0       0.87      0.82      0.84       617
           1       0.82      0.87      0.84       583

    accuracy                           0.84      1200
   macro avg       0.84      0.84      0.84      1200
weighted avg       0.84      0.84      0.84      1200

Best Parameters  {'alpha': 0.5}
Best Score  0.8525
 
Confusion Matrix
[[504 113]
 [ 75 508]]
 
Accuracy of Combinining 

In [149]:
w_mnb=pd.DataFrame(w_mnb, columns=["Word_MNB"])
c_mnb=pd.DataFrame(c_mnb, columns=["Char_MNB"])
wc_mnb=pd.DataFrame(wc_mnb, columns=["Combine Word Char_MNB"])
res_mnb=pd.concat([w_mnb,c_mnb,wc_mnb], axis=1)
res_mnb

Word_MNB  Char_MNB  Combine Word Char_MNB
0           1         1                      1
1           0         0                      0
2           1         1                      1
3           1         1                      1
4           1         1                      1
..        ...       ...                    ...
935         1         1                      1
936         0         1                      1
937         0         0                      0
938         0         0                      0
939         1         1                      1

[940 rows x 3 columns]

# Implementing Logistic Regression 

In [57]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(random_state=40, solver='lbfgs')
param={'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'), 'multi_class':('ovr', 'auto')}
print("Logisitc Regression")
w_lr,c_lr,wc_lr=trainer(LR,param, X, X_char, train, traintest, Y, y_test)

Logisitc Regression
Accuracy of Word n-gram(1,4) : 0.8458333333333333
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       584
           1       0.88      0.81      0.84       616

    accuracy                           0.85      1200
   macro avg       0.85      0.85      0.85      1200
weighted avg       0.85      0.85      0.85      1200

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.8321428571428572
 
Confusion Matrix
[[516  68]
 [117 499]]
 


e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Accuracy of Char n-gram(1,7) : 0.8416666666666667
              precision    recall  f1-score   support

           0       0.81      0.88      0.84       584
           1       0.88      0.80      0.84       616

    accuracy                           0.84      1200
   macro avg       0.84      0.84      0.84      1200
weighted avg       0.84      0.84      0.84      1200

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.8421428571428572
 
Confusion Matrix
[[515  69]
 [121 495]]
 


e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
e:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


Accuracy of Combinining word & Char n-gram 0.8558333333333333
              precision    recall  f1-score   support

           0       0.83      0.88      0.86       584
           1       0.88      0.83      0.86       616

    accuracy                           0.86      1200
   macro avg       0.86      0.86      0.86      1200
weighted avg       0.86      0.86      0.86      1200

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.8478571428571429
 
Confusion Matrix
[[515  69]
 [104 512]]
 


In [ ]:
w_lr=pd.DataFrame(w_lr, columns=["Word_LR"])
c_lr=pd.DataFrame(c_lr, columns=["Char_LR"])
wc_lr=pd.DataFrame(wc_lr, columns=["Combine Word Char_LR"])
res_lr=pd.concat([w_lr,c_lr,wc_lr], axis=1)
res_lr

# Implementing Random Forest Classifier 

In [58]:
from sklearn.ensemble import RandomForestClassifier
RFC=RandomForestClassifier(n_estimators=13)
param={'n_estimators':[10, 20, 30]}
print("Random Forest Classifier")
w_rfc,c_rfc,wc_rfc=trainer(RFC,param, X, X_char, train, traintest, Y, y_test)

Random Forest Classifier
Accuracy of Word n-gram(1,4) : 0.8016666666666666
              precision    recall  f1-score   support

           0       0.77      0.85      0.81       584
           1       0.84      0.76      0.80       616

    accuracy                           0.80      1200
   macro avg       0.80      0.80      0.80      1200
weighted avg       0.81      0.80      0.80      1200

Best Parameters  {'n_estimators': 30}
Best Score  0.8060714285714285
 
Confusion Matrix
[[495  89]
 [149 467]]
 
Accuracy of Char n-gram(1,7) : 0.8316666666666667
              precision    recall  f1-score   support

           0       0.79      0.90      0.84       584
           1       0.89      0.77      0.82       616

    accuracy                           0.83      1200
   macro avg       0.84      0.83      0.83      1200
weighted avg       0.84      0.83      0.83      1200

Best Parameters  {'n_estimators': 30}
Best Score  0.8185714285714286
 
Confusion Matrix
[[524  60]
 [142 474

In [ ]:
w_rfc=pd.DataFrame(w_rfc, columns=["Word_RFC"])
c_rfc=pd.DataFrame(c_rfc, columns=["Char_RFC"])
wc_rfc=pd.DataFrame(wc_rfc, columns=["Combine Word Char_RFC"])
res_rfc=pd.concat([w_rfc,c_rfc,wc_rfc], axis=1)
res_rfc

# Implementing DecisionTreeClassifier


In [59]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier()
param={'criterion':('entropy', 'gini')}
print("Decision Tree Classifier")
w_dtc,c_dtc,wc_dtc=trainer(DTC,param, X, X_char, train, traintest, Y, y_test)

Decision Tree Classifier
Accuracy of Word n-gram(1,4) : 0.7875
              precision    recall  f1-score   support

           0       0.79      0.76      0.78       584
           1       0.78      0.81      0.80       616

    accuracy                           0.79      1200
   macro avg       0.79      0.79      0.79      1200
weighted avg       0.79      0.79      0.79      1200

Best Parameters  {'criterion': 'gini'}
Best Score  0.7967857142857143
 
Confusion Matrix
[[446 138]
 [117 499]]
 
Accuracy of Char n-gram(1,7) : 0.7666666666666667
              precision    recall  f1-score   support

           0       0.75      0.78      0.76       584
           1       0.78      0.76      0.77       616

    accuracy                           0.77      1200
   macro avg       0.77      0.77      0.77      1200
weighted avg       0.77      0.77      0.77      1200

Best Parameters  {'criterion': 'gini'}
Best Score  0.7789285714285714
 
Confusion Matrix
[[453 131]
 [149 467]]
 
Accur

In [ ]:
w_dtc=pd.DataFrame(w_dtc, columns=["Word_DTC"])
c_dtc=pd.DataFrame(c_dtc, columns=["Char_DTC"])
wc_dtc=pd.DataFrame(wc_dtc, columns=["Combine Word Char_DTC"])
res_dtc=pd.concat([w_dtc,c_dtc,wc_dtc], axis=1)
res_dtc

# Implementing AdaBoost 

In [60]:
from sklearn.ensemble import AdaBoostClassifier
ABC=AdaBoostClassifier()
print("AdaBoost Classifier")
param={'n_estimators':[100, 200, 250, 300]}
w_abc,c_abc,wc_abc=trainer(ABC,param, X, X_char, train, traintest, Y, y_test)

AdaBoost Classifier
Accuracy of Word n-gram(1,4) : 0.7958333333333333
              precision    recall  f1-score   support

           0       0.80      0.78      0.79       584
           1       0.79      0.81      0.80       616

    accuracy                           0.80      1200
   macro avg       0.80      0.80      0.80      1200
weighted avg       0.80      0.80      0.80      1200

Best Parameters  {'n_estimators': 200}
Best Score  0.7975
 
Confusion Matrix
[[454 130]
 [115 501]]
 
Accuracy of Char n-gram(1,7) : 0.8266666666666667
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       584
           1       0.84      0.81      0.83       616

    accuracy                           0.83      1200
   macro avg       0.83      0.83      0.83      1200
weighted avg       0.83      0.83      0.83      1200

Best Parameters  {'n_estimators': 300}
Best Score  0.8314285714285714
 
Confusion Matrix
[[491  93]
 [115 501]]
 
Accuracy o

In [ ]:
w_abc=pd.DataFrame(w_abc, columns=["Word_ABC"])
c_abc=pd.DataFrame(c_abc, columns=["Char_ABC"])
wc_abc=pd.DataFrame(wc_abc, columns=["Combine Word Char_ABC"])
res_abc=pd.concat([w_abc,c_abc,wc_abc], axis=1)
res_abc

# Ensemble Approch


In [61]:
from sklearn.ensemble import VotingClassifier

In [62]:
vote_model = VotingClassifier(estimators=[('svcm', svc), ('MNBm', MNB), ('LRm', LR)], voting='hard')
param={}
w_ens,c_ens,wc_ens=trainer(vote_model,param, X, X_char, train, traintest, Y, y_test)

e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Word n-gram(1,4) : 0.8408333333333333
              precision    recall  f1-score   support

           0       0.80      0.91      0.85       584
           1       0.90      0.78      0.83       616

    accuracy                           0.84      1200
   macro avg       0.85      0.84      0.84      1200
weighted avg       0.85      0.84      0.84      1200

Best Parameters  {}
Best Score  0.8217857142857142
 
Confusion Matrix
[[529  55]
 [136 480]]
 


e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Char n-gram(1,7) : 0.8375
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       584
           1       0.91      0.76      0.83       616

    accuracy                           0.84      1200
   macro avg       0.85      0.84      0.84      1200
weighted avg       0.85      0.84      0.84      1200

Best Parameters  {}
Best Score  0.8367857142857142
 
Confusion Matrix
[[535  49]
 [146 470]]
 


e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 

Accuracy of Combinining word & Char n-gram 0.8491666666666666
              precision    recall  f1-score   support

           0       0.81      0.91      0.85       584
           1       0.90      0.80      0.84       616

    accuracy                           0.85      1200
   macro avg       0.85      0.85      0.85      1200
weighted avg       0.85      0.85      0.85      1200

Best Parameters  {}
Best Score  0.8457142857142858
 
Confusion Matrix
[[529  55]
 [126 490]]
 


In [ ]:
w_ens=pd.DataFrame(w_ens, columns=["Word_Ensem"])
c_ens=pd.DataFrame(c_ens, columns=["Char_Ensem"])
wc_ens=pd.DataFrame(wc_ens, columns=["Combine Word Char_Ensem"])
res_ens=pd.concat([w_ens,c_ens,wc_ens], axis=1)
res_ens

In [ ]:
FINAL=pd.concat([res_svm, res_mnb, res_lr, res_rfc, res_dtc, res_abc, res_ens], axis=1)

In [ ]:
FINAL

In [ ]:
FINAL['Word_SVC'] = FINAL['Word_SVC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_SVC'] = FINAL['Char_SVC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_SVC']= FINAL['Combine Word Char_SVC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_MNB'] = FINAL['Word_MNB'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_MNB'] = FINAL['Char_MNB'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_MNB']= FINAL['Combine Word Char_MNB'].map({0 : 'NOT', 1 : 'OFF'})


FINAL['Word_LR'] = FINAL['Word_LR'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_LR'] = FINAL['Char_LR'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_LR']= FINAL['Combine Word Char_LR'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_RFC'] = FINAL['Word_RFC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_RFC'] = FINAL['Char_RFC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_RFC']= FINAL['Combine Word Char_RFC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_DTC'] = FINAL['Word_DTC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_DTC'] = FINAL['Char_DTC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_DTC']= FINAL['Combine Word Char_DTC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_ABC'] = FINAL['Word_ABC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_ABC'] = FINAL['Char_ABC'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_ABC']= FINAL['Combine Word Char_ABC'].map({0 : 'NOT', 1 : 'OFF'})

FINAL['Word_Ensem'] = FINAL['Word_Ensem'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Char_Ensem'] = FINAL['Char_Ensem'].map({0 : 'NOT', 1 : 'OFF'})
FINAL['Combine Word Char_Ensem']= FINAL['Combine Word Char_Ensem'].map({0 : 'NOT', 1 : 'OFF'})

In [ ]:
FINAL

In [ ]:
tam_hasoc1=pd.concat([tam_hasoc, FINAL], axis=1)
tam_hasoc1

In [ ]:
tam_hasoc1.to_csv("malayalam_hasoc_tanglish_test_with_labels.csv")

In [ ]:
df1=pd.read_csv("malayalam_hasoc_tanglish_test_with_labels.csv")

In [ ]:
df1

In [52]:
import tensorflow as tf
from tensorflow import keras

from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [53]:
corpus=X_train
type(corpus)

pandas.core.series.Series

In [54]:
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)

In [55]:
len(all_words)

46628

In [56]:
# However, we do not want the duplicate words.
# We can retrieve all the unique words from a list by passing the list into the set function

unique_words = set(all_words)
print(len(unique_words))

15292


In [57]:
unique_words

{'ootunathu',
 'korona',
 'Pannuvaen',
 'netha',
 'kondadunom',
 'Ad',
 'teriyala',
 'arasiyal',
 'potrukkanga',
 'yudham',
 'neeyalam',
 'aiten',
 'kandara',
 'epdiii',
 'Iyaooo',
 'pathathum',
 'suriya',
 'okuarthuku',
 'peasuriya',
 'kaattave',
 'vidamatranga',
 'next',
 'peysana',
 'therium',
 'naainga',
 'simplicity',
 'Kelambhu',
 'pooja',
 'We',
 'mavanu',
 'thanthanai',
 'ongala',
 'mela',
 'mattrum',
 'maree',
 'saiyaa',
 'apadi',
 'de',
 'ha',
 'aalum',
 'thahappanum',
 'aryan',
 'Kena',
 'natural',
 'viyakuran',
 'narinu',
 'Thalaivaaaaa',
 'ante',
 'highlight',
 'kovathula',
 'SWTY',
 'Modra',
 'thookala',
 'pallu',
 'aaitn',
 'design',
 'winning',
 'moolai',
 'best',
 'mobile',
 'Palaya',
 'Irunthe',
 'nanbana',
 'kamikuthu',
 'kidaikkira',
 'yallarum',
 'Payale',
 'thirumba',
 'nusollitu',
 'pesuradhu',
 'En',
 'poitala',
 'thindukkal',
 'thasamapaagamna',
 'mulai',
 'paakradhu',
 'yethachu',
 'persons',
 'vandhadhum',
 'pannathiga',
 'panns',
 'Creat',
 'thanga',
 'vachi

In [58]:
#we convert all the sentences in our corpus to their numeric form and display them on the console.
#The output looks like this:
vocab_length=15300
embedded_sentences = [one_hot(sent, vocab_length) for sent in corpus]
print(embedded_sentences )

[[4763, 3978, 11098, 3965, 12848, 907, 14323, 5400, 13728, 10047, 10768, 4966], [3226, 13923, 490, 6470, 4502, 6641, 13978, 7012, 631, 10649, 13764, 12388, 5256, 4502, 13978, 13777, 596, 11098, 12729, 6130, 8627, 13842, 9334, 8431, 313, 5055, 659, 1187, 7577, 11974, 11098, 1454, 8134, 11958], [2294, 1124, 11165, 7734, 10132, 3939, 14396, 8597, 10888, 739, 12680, 5426, 3216, 8688, 8813, 14242, 7981, 3065, 8156, 1948], [6552, 8332, 10941, 5552, 13400, 10828, 3065, 13680, 10683, 11015], [8339, 13160, 1790, 954, 4040, 11696, 2802, 8201, 9985, 5598, 11015, 13533], [11576, 11576, 11576, 8791, 4506, 2294, 1594, 11098, 11365, 3281, 12773, 4163], [9288, 2907, 13288, 13261, 6811, 11445, 6297, 14388, 11048, 3801, 4737, 8363, 1790, 9390, 4225, 9328, 3333, 12918, 5454], [7824, 2349, 10897, 13710, 358, 2079, 3868, 12972, 7372, 6381], [10595, 14584, 10193, 1553, 11015, 10983, 10131, 7067], [12529, 12500, 6358, 596, 4879, 907, 6249, 4879, 2891, 10456, 6958, 13978, 14771, 6504, 12529, 3356, 3336, 5256,

In [59]:
embedded_sentences[0]

[4763, 3978, 11098, 3965, 12848, 907, 14323, 5400, 13728, 10047, 10768, 4966]

In [60]:
# The embedding layer expects sentences to be of equal size. However, our encoded sentences are of different sizes.
# One way to make all the sentences of uniform size is to increase the lenght of all the sentences 
# and make it equal to the length of the largest sentence. 

# Let's first find the largest sentence in our corpus and then 
# we will increase the length of all the sentences to the length of the largest sentence.

word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [61]:
length_long_sentence

64

In [62]:
# we can see zeros at the end of the padded sentences.

padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences), len(padded_sentences), padded_sentences.shape

[[ 4763  3978 11098 ...     0     0     0]
 [ 3226 13923   490 ...     0     0     0]
 [ 2294  1124 11165 ...     0     0     0]
 ...
 [12263  2284  2357 ...     0     0     0]
 [  522  3394  7519 ...     0     0     0]
 [ 7022  9053  2652 ...     0     0     0]]


(None, 2800, (2800, 64))

In [63]:
padded_sentences[0]

array([ 4763,  3978, 11098,  3965, 12848,   907, 14323,  5400, 13728,
       10047, 10768,  4966,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0])

In [64]:
X_test.shape

(1200,)

In [65]:
X_test

2936    Itha vida oru nala kaalai dharisanam kedaikath...
2606    Kalngathala oru kirukku koo yan kaatharuthu po...
2441    Thevidiya pullanga ajith oru unmaiya mariyaka ...
3415    Enada ne sonathaye mathi sona thane Dubakur mo...
2658    Encounter panna evanum police ah potu oombathi...
                              ...                        
1607    Eppo Uyir uyire mantharam aachu Last option la...
2759    Mattikuchu mattikuchu mattikuchu ipo vaai pund...
1540    Ops thindukkal Srinivasan enga Mama Romba naal...
418                hey pothum pa romba ah poringa ellarum
1810    Right uh Yara intha pulla ungala vida enna rom...
Name: Msg_without_Stopwords, Length: 1200, dtype: object

In [66]:
test_corpus=X_test
type(test_corpus)
test_corpus

2936    Itha vida oru nala kaalai dharisanam kedaikath...
2606    Kalngathala oru kirukku koo yan kaatharuthu po...
2441    Thevidiya pullanga ajith oru unmaiya mariyaka ...
3415    Enada ne sonathaye mathi sona thane Dubakur mo...
2658    Encounter panna evanum police ah potu oombathi...
                              ...                        
1607    Eppo Uyir uyire mantharam aachu Last option la...
2759    Mattikuchu mattikuchu mattikuchu ipo vaai pund...
1540    Ops thindukkal Srinivasan enga Mama Romba naal...
418                hey pothum pa romba ah poringa ellarum
1810    Right uh Yara intha pulla ungala vida enna rom...
Name: Msg_without_Stopwords, Length: 1200, dtype: object

In [67]:
all_words_test = []
for t_sent in test_corpus:
    test_tokenize_word = word_tokenize(t_sent)
    for word in test_tokenize_word:
            all_words_test.append(word)


In [68]:
all_words_test

['Itha',
 'vida',
 'oru',
 'nala',
 'kaalai',
 'dharisanam',
 'kedaikathu',
 'Poonambajwa',
 'nalla',
 'kaatuva',
 'nu',
 'theriyum',
 'aana',
 'ipadiya',
 'Thoppul',
 'azhagi',
 'Low',
 'hip',
 'naa',
 'ithan',
 'en',
 'Chellam',
 'pant',
 'eraki',
 'nakki',
 'Innu',
 'konja',
 'lose',
 'pannina',
 'kaan',
 'kola',
 'kaachiya',
 'irukum',
 'hairy',
 'spot',
 'Kalngathala',
 'oru',
 'kirukku',
 'koo',
 'yan',
 'kaatharuthu',
 'post',
 'la',
 'Loosu',
 'koothi',
 'yatam',
 'pesuran',
 'Thaioli',
 'Keta',
 'tier',
 'sonna',
 'troll',
 'la',
 'da',
 'kootha',
 'saathitu',
 'kelambu',
 'da',
 'yen',
 'junni',
 'Thevidiya',
 'pullanga',
 'ajith',
 'oru',
 'unmaiya',
 'mariyaka',
 'poi',
 'solluvanga',
 'thayoli',
 'inga',
 'Enada',
 'ne',
 'sonathaye',
 'mathi',
 'sona',
 'thane',
 'Dubakur',
 'modi',
 'madhiri',
 'press',
 'partha',
 'bathil',
 'ilama',
 'odara',
 'madhiriye',
 'unaku',
 'vacha',
 'peruku',
 'artham',
 'keta',
 'ipadi',
 'mulikarayeda',
 'Encounter',
 'panna',
 'evanum',
 

In [69]:
test_unique_words = set(all_words_test)
print(len(test_unique_words))

8324


In [70]:
test_vocab_length=7500
test_embedded_sentences = [one_hot(t_sent, test_vocab_length) for t_sent in test_corpus]
print(test_embedded_sentences)

[[4625, 2183, 4778, 2641, 5837, 2833, 1152, 4484, 3975, 3125, 1663, 3618, 5970, 3481, 2591, 3038, 3387, 5369, 6333, 7295, 1816, 3346, 6976, 5819, 7458, 2220, 810, 392, 5865, 3250, 5754, 400, 7036, 3352, 4290], [2747, 4778, 4553, 3335, 1216, 5533, 4525, 5698, 7182, 6858, 4974, 1696, 3340, 5953, 2178, 3543, 4134, 5698, 2203, 5843, 1436, 1069, 2203, 1968, 2837], [4268, 6702, 2104, 4778, 5340, 3608, 728, 3064, 1705, 42], [838, 6429, 2401, 6696, 935, 5954, 2629, 2634, 5392, 5692, 45, 2367, 2424, 5270, 3593, 6823, 5687, 3044, 235, 5953, 5175, 4830], [3733, 1140, 5332, 2481, 7445, 4402, 4859, 790, 4984, 585, 5710, 3404, 5336, 1824, 1897, 4304, 2793, 2975, 1663, 1197, 1116, 7445, 4814, 4407, 1389, 3785, 2281, 2481, 434, 2440, 4097, 12], [681, 702, 823, 4968, 2203, 5289, 7415, 4952, 2203, 7026, 5434, 4778, 5609, 249, 4268, 3470, 4778, 2416, 6917, 7026, 951, 2489, 4952, 7182, 5583], [4665, 828, 4641, 880, 691, 3249, 6692, 4279, 5228, 6406, 5761, 820, 5761, 1968, 187, 2394, 3468, 5616, 4863], [19

In [71]:
test_padded_sentences = pad_sequences(test_embedded_sentences, length_long_sentence, padding='post')
print(test_padded_sentences), len(test_padded_sentences), test_padded_sentences.shape

[[4625 2183 4778 ...    0    0    0]
 [2747 4778 4553 ...    0    0    0]
 [4268 6702 2104 ...    0    0    0]
 ...
 [5879 5118 2657 ...    0    0    0]
 [3775 6575 6803 ...    0    0    0]
 [ 630 1828  723 ...    0    0    0]]


(None, 1200, (1200, 64))

In [72]:
sentiments=y_train
sentiments=sentiments.to_numpy()
type(sentiments)

numpy.ndarray

In [73]:
model = keras.Sequential([
    keras.layers.Embedding(vocab_length, 200, input_length=length_long_sentence),
    keras.layers.Flatten(),
    keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 64, 200)           3060000   
_________________________________________________________________
flatten (Flatten)            (None, 12800)             0         
_________________________________________________________________
dense (Dense)                (None, 1)                 12801     
Total params: 3,072,801
Trainable params: 3,072,801
Non-trainable params: 0
_________________________________________________________________


In [74]:
model.fit(padded_sentences, sentiments, epochs=4, verbose=1)

Train on 2800 samples
Epoch 1/4
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2800/2800 [==============================] - 8s 3ms/sample - loss: 0.6607 - accuracy: 0.6329
Epoch 2/4
2800/2800 [==============================] - 7s 2ms/sample - loss: 0.3610 - accuracy: 0.9164
Epoch 3/4
2800/2800 [==============================] - 7s 3ms/sample - loss: 0.1292 - accuracy: 0.9761
Epoch 4/4
2800/2800 [==============================] - 7s 3ms/sample - loss: 0.0555 - accuracy: 0.9921


In [75]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 99.535716


In [76]:
ytest=y_test.to_numpy()
test_padded_sentences.shape, ytest.shape

((1200, 64), (1200,))

In [77]:
model.evaluate(test_padded_sentences, ytest)

1200/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.7356143808364868, 0.5316667]

In [78]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score

In [79]:
yhat_probs=model.predict(test_padded_sentences, verbose=0)
yhat_probs

array([[0.5255144 ],
       [0.67021465],
       [0.5371378 ],
       ...,
       [0.2867465 ],
       [0.5913381 ],
       [0.5136974 ]], dtype=float32)

In [80]:
yhat_classes=model.predict_classes(test_padded_sentences, verbose=0)
yhat_classes

array([[1],
       [1],
       [1],
       ...,
       [0],
       [1],
       [1]])

In [81]:
cm=tf.math.confusion_matrix(ytest, yhat_classes)
cm

<tf.Tensor: id=2689, shape=(2, 2), dtype=int32, numpy=
array([[339, 278],
       [284, 299]])>

In [82]:
accuracy = accuracy_score(ytest, yhat_classes)
print('Accuracy: %f' % accuracy)

precision = precision_score(ytest, yhat_classes)
print('Precision: %f' % precision)

recall = recall_score(ytest, yhat_classes)
print('Recall: %f' % recall)

f1 = f1_score(ytest, yhat_classes)
print('F1 score: %f' % f1)

Accuracy: 0.531667
Precision: 0.518198
Recall: 0.512864
F1 score: 0.515517
